In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import os
from IPython.display import display
import scipy as sp

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

pd.options.display.max_columns = None   # To see the entire columns of dataframes
pd.options.display.max_rows = 100

In [3]:
train_combat = pd.read_csv("C:/Users/user/Desktop/bc_data/train_combat.csv")
train_payment = pd.read_csv("C:/Users/user/Desktop/bc_data/train_payment.csv")
train_pledge = pd.read_csv("C:/Users/user/Desktop/bc_data/train_pledge.csv")
train_trade = pd.read_csv("C:/Users/user/Desktop/bc_data/train_trade.csv")
train_activity = pd.read_csv("C:/Users/user/Desktop/bc_data/train_activity.csv")
train_label = pd.read_csv("C:/Users/user/Desktop/bc_data/train_label.csv")

In [4]:
# Copy files in case of retrieving the original ones
combat = train_combat.copy()
pledge = train_pledge.copy()
payment = train_payment.copy()
trade = train_trade.copy()
activity = train_activity.copy()

In [8]:
label = train_label["acc_id"]

In [9]:
combat[combat["acc_id"].isin(label)].head()

,day,acc_id,char_id,server,class,level,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent
0,1,13809,54861,ap,2,13,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
1,1,13809,256332,ap,2,13,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
2,1,13809,307293,ap,3,14,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
3,1,13809,374964,ap,7,16,0.0,0.0,0.0,0.0,0.0,0.112612,0.098129
4,1,13809,117917,ap,2,11,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000

In [15]:
# Total amount spent per account the whole period
train_label["total_spent"] = train_label["survival_time"] * train_label["amount_spent"]

In [16]:
combat[combat["acc_id"].isin(label)] # label에 있는 숫자만 골라냄

,day,acc_id,char_id,server,class,level,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent
0,1,13809,54861,ap,2,13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,13809,256332,ap,2,13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,1,13809,307293,ap,3,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,1,13809,374964,ap,7,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.112612,0.098129
4,1,13809,117917,ap,2,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,1,62835,129987,am,2,17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,1,62835,74659,am,4,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,1,62835,179366,am,1,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,1,62835,157318,am,2,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,1,62835,394244,am,5,10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,1,54241,316971,ag,2,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,1,88683,299973,ar,0,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,1,80158,211359,ap,2,17,0.577658,0.000000,1.183064,0.479728,0.000000,0.675669,1.079416
13,1,30386,309343,as,7,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,1,30386,29625,as,3,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,1,16629,311417,ae,0,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.225223,0.098129
16,1,16629,26567,ae,2,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,1,16629,53462,ae,3,16,0.000000,3.701425,0.000000,0.000000,0.000000,0.000000,1.079416
18,1,16629,149458,ae,1,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,1,10931,236388,an,1,17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,1,115006,171038,az,5,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,1,115006,217404,ay,5,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,1,115006,21515,bd,1,12,0.000000,0.000000,0.000000,0.000000,0.000000,1.013504,0.785030
23,1,149,280049,al,7,17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,1,149,248148,al,3,13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,1,37405,109101,ab,2,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,1,64435,181773,al,6,14,0.000000,0.000000,0.000000,0.000000,0.000000,1.351338,0.883159
27,1,128300,187302,av,1,17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,1,74305,343563,an,1,17,2.310633,0.000000,0.000000,0.000000,0.000000,14.526887,1.864446
29,1,74305,130375,an,2,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,1,74305,343563,bn,1,17,0.000000,0.000000,0.000000,0.000000,0.000000,0.675669,0.490644
31,1,36350,10163,ax,2,13,0.000000,0.000000,1.183064,0.000000,0.000000,0.000000,0.098129
32,1,77519,176073,ae,1,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,1,77519,212993,ae,5,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.112612,0.098129
34,1,77519,323065,ae,7,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,1,77519,363511,ae,5,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.112612,0.098129
36,1,66631,397337,ai,1,17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,1,104613,183473,am,1,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,1,127811,14049,bd,4,11,0.000000,0.000000,0.000000,0.000000,0.000000,1.013504,0.883159
39,1,127811,353116,az,1,9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40,1,127811,142589,ay,2,10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
41,1,127811,370509,ay,4,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,1,127811,196677,bb,1,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,1,127811,49693,az,3,10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,1,27245,165282,az,1,17,0.000000,0.000000,0.000000,0.479728,0.000000,0.112612,0.196258
45,1,80943,324569,ay,2,13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
46,1,80943,360570,ay,4,17,0.064184,0.000000,0.000000,0.479728,0.000000,0.000000,0.196258
47,1,21760,176604,aq,5,17,3.273396,3.416700,0.000000,0.000000,0.000000,0.000000,3.238249
48,1,21760,252457,aq,5,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
49,1,91750,144587,ad,2,17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1574621,10,34847,110643,bb,3,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574622,10,34847,200991,bc,4,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574623,10,34847,16802,az,4,13,0.000000,0.000000,1.183064,0.000000,0.000000,0.563058,0.490644
1574624,10,70480,162229,az,3,13,0.000000,0.000000,3.549193,0.000000,0.000000,0.675669,0.588773
1574625,10,70480,209128,bc,3,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574626,10,70480,275709,bb,4,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574627,10,128036,321945,af,2,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.112612,0.098129
1574628,10,57613,157133,bb,3,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574629,10,87077,381584,ao,1,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574630,10,52954,110730,ae,2,16,0.000000,0.000000,0.000000,0.479728,0.000000,0.000000,0.098129
1574631,10,26932,122647,at,5,16,0.000000,0.000000,0.000000,0.000000,0.000000,1.126115,0.785030
1574632,10,22039,184456,am,2,16,0.000000,0.000000,0.000000,0.479728,0.000000,0.000000,0.098129
1574633,10,128355,347849,al,2,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574634,10,155,89374,ad,3,16,0.000000,0.000000,2.366129,0.000000,0.000000,0.337835,0.392515
1574635,10,61285,11380,an,1,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574636,10,96812,73115,ab,0,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574637,10,44820,251810,at,5,16,0.000000,0.000000,0.000000,0.000000,0.000000,1.013504,0.588773
1574638,10,62269,98756,ao,3,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574639,10,49903,352098,ad,0,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574640,10,97331,303315,ar,4,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574641,10,64877,283410,bd,7,14,0.000000,0.000000,0.000000,0.000000,0.000000,1.126115,0.490644
1574642,10,4749,14676,ab,3,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574643,10,1998,361147,ax,3,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574644,10,100485,287275,bd,4,12,0.000000,0.000000,0.000000,0.000000,0.000000,0.788281,0.686901
1574645,10,92179,27485,ab,3,11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574646,10,92179,151719,ab,3,16,0.000000,0.000000,0.000000,0.000000,0.000000,1.013504,0.686901
1574647,10,46126,252824,ac,0,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574648,10,90014,1296,ab,3,15,0.000000,0.000000,0.000000,0.000000,0.000000,1.914396,0.686901
1574649,10,51495,214396,bd,5,12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574650,10,109154,42053,ak,3,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.337835,0.294386
1574651,10,7837,154333,au,4,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574652,10,80187,178223,bb,5,13,0.000000,0.000000,0.000000,0.000000,6.199136,0.000000,0.098129
1574653,10,80187,389026,az,4,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574654,10,6611,123392,aa,4,16,0.000000,0.000000,0.000000,0.479728,0.000000,0.000000,0.098129
1574655,10,22399,282670,bd,4,12,0.000000,0.000000,0.000000,0.000000,0.000000,0.225223,0.196258
1574656,10,66983,345916,ay,3,14,0.000000,0.000000,1.183064,0.000000,0.000000,0.000000,0.098129
1574657,10,66983,11728,bc,4,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574658,10,66983,372053,bb,4,15,0.000000,0.000000,1.183064,0.000000,0.000000,0.000000,0.098129
1574659,10,76321,327759,ay,3,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.112612,0.098129
1574660,10,76321,352802,bc,4,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574661,10,20624,364869,an,2,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574662,10,106213,204048,az,3,16,0.000000,0.000000,1.183064,0.000000,0.000000,0.000000,0.098129
1574663,10,70406,135843,az,4,16,0.000000,0.000000,0.000000,5.277005,0.000000,0.112612,0.196258
1574664,10,99635,254772,av,1,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574665,10,17661,128814,bd,2,14,0.000000,0.000000,0.000000,0.000000,0.000000,0.337835,0.294386
1574666,10,21604,179760,az,3,15,0.000000,0.000000,0.000000,4.797278,0.000000,0.000000,0.098129
1574667,10,73622,36541,az,3,15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574668,10,104426,23384,ai,7,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574669,10,85674,111923,an,4,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1574670,10,11343,52069,ao,5,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [17]:
# No need to keep the rows whose "acc_id" does not appear in Label data
combat = combat[combat["acc_id"].isin(label)]
pledge = pledge[pledge["acc_id"].isin(label)]
payment = payment[payment["acc_id"].isin(label)]
trade = trade[trade["source_acc_id"].isin(label)]
trade = trade[trade["target_acc_id"].isin(label)]
activity = activity[activity["acc_id"].isin(label)]
# 요렇게 하면 달라지는 게 무엇인가?

## Common Features

In [18]:
# The number of characters per account
all_char = pd.concat([train_combat[["char_id", "acc_id"]], train_pledge[["char_id", "acc_id"]], train_activity[["char_id", "acc_id"]]])
char_count = all_char.groupby("char_id")["acc_id"].count()
char_count.head()

char_id
2     2
3    24
5    20
7    14
9     2
Name: acc_id, dtype: int64

In [19]:
all_char.sort_values(by='acc_id')['acc_id'].nunique()

40000

In [20]:
all_char.sort_values(by='acc_id')['char_id'].nunique()

150960

In [21]:
all_char.groupby('acc_id')['char_id'].nunique().head()

acc_id
2     1
5     3
8     7
17    4
20    2
Name: char_id, dtype: int64

In [22]:
all_char[all_char['acc_id']==8]['char_id'].nunique()

7

In [23]:
char_count = pd.DataFrame({"char_count" : char_count})  # in case of merging

In [24]:
all_char.head()
# 전체 char_id에 따른 acc_id 묶어놓은 것!

   char_id  acc_id
0    54861   13809
1   256332   13809
2   307293   13809
3   374964   13809
4   117917   13809

In [25]:
char_count.head()
# 이것의 의미?
# 이거 acc_id가 나와야 하는 것 아님?

         char_count
char_id
2                 2
3                24
5                20
7                14
9                 2

In [26]:
# Find all the unique servers
total_server = pd.concat([train_combat["server"], train_pledge["server"], train_trade["server"], train_activity["server"]])
total_server.head()

0    ap
1    ap
2    ap
3    ap
4    ap
Name: server, dtype: object

In [27]:
server_list = total_server.unique()
server_list

array(['ap', 'am', 'ag', 'ar', 'as', 'ae', 'an', 'az', 'ay', 'bd', 'al',
       'ab', 'av', 'bn', 'ax', 'ai', 'bb', 'aq', 'ad', 'ac', 'bk', 'ak',
       'bl', 'aw', 'aj', 'bm', 'bc', 'at', 'aa', 'bo', 'ao', 'ah', 'au',
       'af', 'bj', 'br', 'bp', 'bg', 'bs', 'bi'], dtype=object)

In [28]:
# Encode servers into integer values
le = LabelEncoder()
le.fit(server_list)
for df in [combat, pledge, trade, activity]:
    df["server"] = le.transform(df["server"])
# server column을 categorial하게 만들어줌!

In [29]:
df.head()

,day,acc_id,char_id,server,playtime,npc_kill,solo_exp,party_exp,quest_exp,boss_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
0,1,75001,397380,0,1.459994,0.000000,0.000000,0.000000,0.000000,0,0.00000,0.000000,0.0,0.0,1.119053,0.033934,0.0
1,1,75001,216231,0,0.286785,2.244221,0.046989,0.000000,0.000000,0,0.00000,0.000000,0.0,0.0,0.000000,-0.013933,0.0
2,1,75711,308769,0,1.049964,2.951697,0.321164,0.166247,0.003463,1,0.24537,0.246819,0.0,0.0,0.000000,-0.001983,0.0
3,1,72230,387177,0,0.232272,4.035346,0.098944,0.000000,0.001732,0,0.00000,0.000000,0.0,0.0,0.000000,-0.028823,0.0
4,1,34253,339862,0,1.102106,0.595805,0.003371,0.000000,0.000000,0,0.00000,0.000000,0.0,0.0,0.000000,0.011752,0.0

## Trade

In [30]:
trade.rename(columns={"source_acc_id" : "acc_id"}, inplace=True)

In [31]:
trade.head()

,day,time,type,server,acc_id,source_char_id,target_acc_id,target_char_id,item_type,item_amount,item_price
3,1,14:37:50,1,17,78411,226143,80350,34764,adena,6.695623e-03,NaN
6,1,14:24:53,1,11,18212,164230,38145,34209,accessory,8.034747e-08,NaN
9,1,20:20:02,0,0,54445,383477,97930,197911,etc,1.339125e-05,0.013231
10,1,02:05:57,0,1,69336,31464,119150,28903,etc,2.678249e-06,0.032727
11,1,23:04:25,1,4,18640,272906,78425,46788,adena,3.077308e-01,NaN

In [32]:
# 같은 계정이면 같은 네트워크 그룹을 가질 확률이 높음 : 아이디 하나로 묶어도 상관없을듯
trade.drop(["source_char_id", "target_char_id"], axis=1, inplace=True)

In [33]:
trade.head()

,day,time,type,server,acc_id,target_acc_id,item_type,item_amount,item_price
3,1,14:37:50,1,17,78411,80350,adena,6.695623e-03,NaN
6,1,14:24:53,1,11,18212,38145,accessory,8.034747e-08,NaN
9,1,20:20:02,0,0,54445,97930,etc,1.339125e-05,0.013231
10,1,02:05:57,0,1,69336,119150,etc,2.678249e-06,0.032727
11,1,23:04:25,1,4,18640,78425,adena,3.077308e-01,NaN

In [34]:
trade["item_price"].fillna(trade["item_price"].median(), inplace=True)
# 이렇게 해도 되는가?
# 일단 missing으로 해야하는 게 아닌가?

In [35]:
trade['item_price'].isnull().sum()

0

In [36]:
trade.head()

,day,time,type,server,acc_id,target_acc_id,item_type,item_amount,item_price
3,1,14:37:50,1,17,78411,80350,adena,6.695623e-03,0.018362
6,1,14:24:53,1,11,18212,38145,accessory,8.034747e-08,0.018362
9,1,20:20:02,0,0,54445,97930,etc,1.339125e-05,0.013231
10,1,02:05:57,0,1,69336,119150,etc,2.678249e-06,0.032727
11,1,23:04:25,1,4,18640,78425,adena,3.077308e-01,0.018362

In [37]:
# Categorize transaction time
# categroial로
bins = [0, 60000, 120000, 180000, 239999]
bin_label = [0, 1, 2, 3]   
trade["time_bin"] = pd.cut(pd.to_numeric(trade["time"].str.replace(":", "")), bins=bins, labels=bin_label)
# Those who play during the time other than evening must be differentiated
trade["time_bin"] = trade["time_bin"].map({0:1, 1:1, 2:1, 3:0}) 
trade.drop("time", axis=1, inplace=True)

In [38]:
trade.head()

,day,type,server,acc_id,target_acc_id,item_type,item_amount,item_price,time_bin
3,1,1,17,78411,80350,adena,6.695623e-03,0.018362,1.0
6,1,1,11,18212,38145,accessory,8.034747e-08,0.018362,1.0
9,1,0,0,54445,97930,etc,1.339125e-05,0.013231,0.0
10,1,0,1,69336,119150,etc,2.678249e-06,0.032727,1.0
11,1,1,4,18640,78425,adena,3.077308e-01,0.018362,0.0

In [39]:
# trade['time_bin'] = trade['time_bin'].astype('category')
trade['time_bin'] = trade['time_bin'].astype('float64')

In [40]:
trade.info() # 카테고리로 변경하면 time_bin을 pivot table에서 사용못함

<class 'pandas.core.frame.DataFrame'>
Int64Index: 834491 entries, 3 to 2245192
Data columns (total 9 columns):
day              834491 non-null int64
type             834491 non-null int64
server           834491 non-null int32
acc_id           834491 non-null int64
target_acc_id    834491 non-null int64
item_type        834491 non-null object
item_amount      834491 non-null float64
item_price       834491 non-null float64
time_bin         834475 non-null float64
dtypes: float64(3), int32(1), int64(4), object(1)
memory usage: 60.5+ MB

In [41]:
# Total price per each trade
# 현재는 median으로 대체된 값이 곱해져 있음을 기억해야 함
trade["total_item_price"] = trade["item_amount"] * trade["item_price"]

In [42]:
trade.head()

,day,type,server,acc_id,target_acc_id,item_type,item_amount,item_price,time_bin,total_item_price
3,1,1,17,78411,80350,adena,6.695623e-03,0.018362,1.0,1.229472e-04
6,1,1,11,18212,38145,accessory,8.034747e-08,0.018362,1.0,1.475367e-09
9,1,0,0,54445,97930,etc,1.339125e-05,0.013231,0.0,1.771791e-07
10,1,0,1,69336,119150,etc,2.678249e-06,0.032727,1.0,8.765042e-08
11,1,1,4,18640,78425,adena,3.077308e-01,0.018362,0.0,5.650656e-03

In [43]:
# Make two trade DataFrames for each source and target
source_trade = trade.drop("target_acc_id", axis=1)
target_trade = trade.drop("acc_id", axis=1)
target_trade.rename(columns={"target_acc_id" : "acc_id"}, inplace=True)

In [44]:
source_trade.head()
# source id의 거래내역

,day,type,server,acc_id,item_type,item_amount,item_price,time_bin,total_item_price
3,1,1,17,78411,adena,6.695623e-03,0.018362,1.0,1.229472e-04
6,1,1,11,18212,accessory,8.034747e-08,0.018362,1.0,1.475367e-09
9,1,0,0,54445,etc,1.339125e-05,0.013231,0.0,1.771791e-07
10,1,0,1,69336,etc,2.678249e-06,0.032727,1.0,8.765042e-08
11,1,1,4,18640,adena,3.077308e-01,0.018362,0.0,5.650656e-03

In [45]:
target_trade.head()
# target id의 거래내역

,day,type,server,acc_id,item_type,item_amount,item_price,time_bin,total_item_price
3,1,1,17,80350,adena,6.695623e-03,0.018362,1.0,1.229472e-04
6,1,1,11,38145,accessory,8.034747e-08,0.018362,1.0,1.475367e-09
9,1,0,0,97930,etc,1.339125e-05,0.013231,0.0,1.771791e-07
10,1,0,1,119150,etc,2.678249e-06,0.032727,1.0,8.765042e-08
11,1,1,4,78425,adena,3.077308e-01,0.018362,0.0,5.650656e-03

In [46]:
# Total number of trade occurence per account the whole period

source_trade_count = source_trade["acc_id"].value_counts()
target_trade_count = target_trade["acc_id"].value_counts()

In [47]:
source_trade_count.head()

50413     3552
111023    2496
59264     2039
120428    1834
97968     1727
Name: acc_id, dtype: int64

In [48]:
target_trade_count.head()

50413     3480
120428    2854
62350     1972
91062     1848
111023    1741
Name: acc_id, dtype: int64

In [49]:
source_trade_count = pd.DataFrame({"acc_id" : source_trade_count.index,
                                   "count" : source_trade_count})    # Make a dataframe to merge based on "acc_id"
target_trade_count = pd.DataFrame({"acc_id" : target_trade_count.index,
                                   "count" : target_trade_count})

In [50]:
source_trade_count.head()

        acc_id  count
50413    50413   3552
111023  111023   2496
59264    59264   2039
120428  120428   1834
97968    97968   1727

In [51]:
target_trade_count.head()

        acc_id  count
50413    50413   3480
120428  120428   2854
62350    62350   1972
91062    91062   1848
111023  111023   1741

In [52]:
trade_count = pd.merge(source_trade_count, target_trade_count, on = "acc_id")
trade_count["count"] = trade_count["count_x"] + trade_count["count_y"]
trade_count.head()

   acc_id  count_x  count_y  count
0   50413     3552     3480   7032
1  111023     2496     1741   4237
2   59264     2039      191   2230
3  120428     1834     2854   4688
4   97968     1727      870   2597

In [53]:
trade_count.drop(["count_x", "count_y"], axis=1, inplace=True)
trade_count.head()

   acc_id  count
0   50413   7032
1  111023   4237
2   59264   2230
3  120428   4688
4   97968   2597

In [54]:
# Remove columns that do not seem necessary
# 서버는 necessary할 수도 있지 않을까?
trade.drop(["target_acc_id", "item_type", "item_amount", "item_price"], axis=1, inplace=True)

In [55]:
pd.pivot_table(data=trade, index=["acc_id", "day"], \
               values=["time_bin", "total_item_price"], aggfunc=sum).head(20)

            time_bin  total_item_price
acc_id day
2      1         3.0      1.867780e-06
       2         1.0      6.393257e-03
       3         1.0      1.249094e-06
       5         0.0      1.998430e-09
       12        0.0      5.005340e-09
       14        1.0      4.506484e-09
       16        1.0      1.439520e-10
       19        1.0      2.336234e-09
8      11        1.0      2.813892e-08
17     6         0.0      1.570696e-11
       7         1.0      8.765042e-14
       9         0.0      9.465444e-10
       11        1.0      5.840799e-10
       15        0.0      9.566418e-13
       17        0.0      7.205816e-10
       18        1.0      2.758734e-11
       19        1.0      4.917890e-02
       20        0.0      3.402840e-11
       23        0.0      1.714943e-11
       24        5.0      2.950747e-02

In [56]:
pd.pivot_table(data=trade, index=["acc_id", "day"], values=["type"]).head(20)
# 상점이냐, 개인거래냐

            type
acc_id day
2      1     0.0
       2     1.0
       3     0.0
       5     0.0
       12    0.0
       14    0.0
       16    0.0
       19    0.0
8      11    0.0
17     6     0.0
       7     0.0
       9     0.0
       11    0.0
       15    0.0
       17    0.0
       18    0.0
       19    1.0
       20    0.0
       23    0.0
       24    0.2

In [57]:
trade = pd.concat(
    [pd.pivot_table(data=trade, index=["acc_id", "day"], values=["time_bin", "total_item_price"], aggfunc=sum), # sum all the prices
    pd.pivot_table(data=trade, index=["acc_id", "day"], values=["type"])], # mean for trade type
    axis=1)

In [58]:
trade.head(20) # trade!

            time_bin  total_item_price  type
acc_id day
2      1         3.0      1.867780e-06   0.0
       2         1.0      6.393257e-03   1.0
       3         1.0      1.249094e-06   0.0
       5         0.0      1.998430e-09   0.0
       12        0.0      5.005340e-09   0.0
       14        1.0      4.506484e-09   0.0
       16        1.0      1.439520e-10   0.0
       19        1.0      2.336234e-09   0.0
8      11        1.0      2.813892e-08   0.0
17     6         0.0      1.570696e-11   0.0
       7         1.0      8.765042e-14   0.0
       9         0.0      9.465444e-10   0.0
       11        1.0      5.840799e-10   0.0
       15        0.0      9.566418e-13   0.0
       17        0.0      7.205816e-10   0.0
       18        1.0      2.758734e-11   0.0
       19        1.0      4.917890e-02   1.0
       20        0.0      3.402840e-11   0.0
       23        0.0      1.714943e-11   0.0
       24        5.0      2.950747e-02   0.2

## Pledge(혈맹)

In [64]:
pledge.head()

,day,acc_id,char_id,server,pledge_id,play_char_cnt,combat_char_cnt,pledge_combat_cnt,random_attacker_cnt,random_defender_cnt,same_pledge_cnt,temp_cnt,etc_cnt,combat_play_time,non_combat_play_time
0,1,106660,345122,0,381,0.036089,0.036089,0.0,0.0,0.0,0.0,0.000000,0.007078,0.027568,0.000000
1,1,46383,161773,0,10892,0.036089,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.006139
2,1,18495,321373,0,13705,0.036089,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000347
3,1,118293,366707,0,2982,0.036089,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.001042
4,1,50421,158063,0,27104,0.216536,0.072179,0.0,0.0,0.0,0.0,0.098883,0.056626,0.083978,0.000000

In [68]:
pledge[pledge['acc_id']==46383].head()

,day,acc_id,char_id,server,pledge_id,play_char_cnt,combat_char_cnt,pledge_combat_cnt,random_attacker_cnt,random_defender_cnt,same_pledge_cnt,temp_cnt,etc_cnt,combat_play_time,non_combat_play_time
1,1,46383,161773,0,10892,0.036089,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.006139
18811,1,46383,210718,17,5135,0.036089,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.004633
54866,2,46383,210718,17,5135,0.036089,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.042162
91916,3,46383,210718,17,5135,0.036089,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001274
93289,3,46383,47841,17,35276,0.036089,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000463

In [ ]:
# 위의 상황을 보면 server가 다른데 char_id가 같은 경우가 존재합니다!

In [62]:
# The number of members in each pledge
pledge_num_people = pledge["pledge_id"].value_counts()
pledge_num_people.head()
# 혈맹이 같은 사람들끼리의 정보

36551    4133
13214    3355
17546    3049
10843    2744
33924    2633
Name: pledge_id, dtype: int64

# 질문 : 여기에서 server를 없애도 되나요?
## server 별로 분류해야 할까요...?

In [72]:
# 일단은 server를 제거하지 않았습니다!
pledge.drop(["char_id", "pledge_id"], axis=1, inplace=True)

In [74]:
pledge = pd.pivot_table(data=pledge, index=['server','acc_id', "day"], aggfunc=sum)

In [75]:
pledge

                   combat_char_cnt  combat_play_time   etc_cnt  \
server acc_id day
0      75     8           1.190948          1.883065  0.332678
              15          0.505250          0.451973  0.276052
              16          0.288715          0.404134  0.063704
              17          0.721786          0.902671  0.254818
              18          0.902233          0.979004  0.325600
              19          0.613518          1.014680  0.233583
              20          0.288715          0.473981  0.155722
              21          0.433072          0.629889  0.375148
              22          0.505250          0.706801  0.198191
              23          0.433072          0.526336  0.247739
              24          0.396983          0.498884  0.084939
              25          0.721786          0.869891  0.148644
              26          0.974412          1.030433  0.686592
              27          0.613518          1.163407  0.396383
              28          0.685697          1.124835  0.587496
       161    4           0.000000          0.000000  0.000000
              18          0.000000          0.000000  0.000000
       260    8           0.000000          0.000000  0.000000
              9           0.000000          0.000000  0.000000
              10          0.000000          0.000000  0.000000
              11          0.000000          0.000000  0.000000
              12          0.000000          0.000000  0.000000
              13          0.000000          0.000000  0.000000
              15          0.036089          0.020965  0.007078
              16          0.036089          0.013436  0.000000
              17          0.036089          0.025599  0.007078
              21          0.036089          0.015753  0.000000
              23          0.000000          0.000000  0.000000
              27          0.000000          0.000000  0.000000
              28          0.000000          0.000000  0.000000
       309    1           1.190948          3.423039  0.906018
              2           2.417984          6.535071  2.328749
              3           2.057091          6.258814  2.449080
              4           1.840555          5.095639  1.366105
              5           2.021002          5.387302  2.328749
              6           1.551841          5.890240  1.047583
              7           1.660109          5.518654  1.259931
              8           2.526252          4.913321  4.777829
              9           2.237538          7.321796  1.564297
              10          2.562342          7.397665  2.314593
              11          2.778878          7.587165  3.496663
              12          2.670610          7.050867  5.719238
              13          2.093181          6.407426  1.380262
              14          2.309716          6.891252  3.114437
              15          2.417984          4.641929  4.338977
              16          2.417984          6.268428  1.486436
              17          2.454074          7.229131  2.781758
              18          2.201448          7.062682  1.720018
              19          2.129270          6.207385  0.877705
              20          2.165359          5.927538  0.941409
...                            ...               ...       ...
38     126699 24          0.938322          0.305910  0.056626
              25          0.685697          0.324327  0.028313
              26          0.180447          0.050502  0.000000
              27          0.000000          0.000000  0.000000
       126817 5           0.433072          0.201083  0.049548
              12          0.396983          0.213129  0.028313
              19          0.360893          0.145252  0.007078
       127120 2           0.144357          0.033359  0.000000
              3           0.252625          0.059885  0.014157
              4           0.216536          0.059885  0.000000
              5           0.072179          0.004633  0.000000
              8           0.108268          0.081198  0.000000
              9           0.180447          0.020039  0.000000
              14          0.180447          0.072047  0.007078
              15          0.180447          0.099962  0.070783
              16          0.216536          0.097182  0.000000
              17          0.324804          0.073553  0.077861
              18          0.252625          0.088495  0.028313
              19          0.180447          0.010772  0.042470
              20          0.144357          0.045406  0.000000
              23          0.324804          0.094518  0.007078
              24          0.396983          0.176527  0.092017
              25          0.252625          0.148148  0.063704
              26          0.180447          0.046448  0.106174
              28          0.216536          0.151044  0.028313
       127560 1           0.216536          0.052124  0.000000
              3           0.396983          0.050850  0.000000
              7           0.288715          0.035792  0.127409
              11          0.180447          0.050850  0.000000
              12          0.541340          0.104595  0.226504
              25          0.288715          0.070773  0.056626
       127648 6           0.108268          0.028610  0.000000
              7           0.288715          0.035792  0.127409
              9           0.144357          0.030695  0.000000
              11          0.180447          0.050850  0.000000
              22          0.000000          0.000000  0.000000
       128817 12          0.144357          0.021660  0.148644
              19          0.252625          0.107144  0.000000
              26          0.108268          0.081777  0.021235
       129429 12          0.505250          0.325369  0.092017
              26          0.577429          0.208612  0.092017
       129629 19          0.721786          0.329192  0.063704
       129716 5           0.396983          0.102163  0.106174
              12          0.360893          0.138186  0.000000
              19          0.613518          0.226102  0.134487
       129982 19          0.613518          0.342860  0.014157
       130027 12          0.685697          0.290388  0.014157
       130434 1           0.216536          0.052124  0.000000
              2           0.216536          0.030927  0.014157
              3           0.396983          0.050850  0.000000

                   non_combat_play_time  play_char_cnt  pledge_combat_cnt  \
server acc_id day
0      75     8                0.000000       4.402897           0.043710
              15               0.000000       1.118769           0.000000
              16               0.000000       1.190948           0.020034
              17               0.000000       2.165359           0.000000
              18               0.000000       2.345806           0.018213
              19               0.000000       2.417984           0.000000
              20               0.000000       1.732287           0.000000
              21               0.000000       2.273627           0.000000
              22               0.000000       2.021002           0.000000
              23               0.000000       2.129270           0.000000
              24               0.000000       1.912734           0.000000
              25               0.000000       2.742788           0.000000
              26               0.000000       2.417984           0.003643
              27               0.000000       2.562342           0.000000
              28               0.000000       2.165359           0.000000
       161    4                0.012278       0.144357           0.000000
              18               0.009614       0.216536           0.000000
       260    8                0.007992       0.108268           0.000000
              9                0.008687       0.144357           0.000000
              10               0.040657       0.360893           0.000000
              11               0.004054       0.144357           0.000000
              12               0.016911       0.144357           0.000000
              13               0.026873       0.144357           0.000000
              15               0.000000       0.144357           0.000000
              16               0.000000       0.072179           0.000000
              17               0.000000       0.072179           0.000000
              21               0.000000       0.072179           0.000000
              23               0.014479       0.072179           0.000000
              27               0.093128       2.165359           0.000000
              28               0.015637       0.072179           0.000000
       309    1                0.000000       3.645021           0.000000
              2                0.000000       4.294629           0.216731
              3                0.000000       4.150272           0.060102
              4                0.000000       3.464575           0.054638
              5                0.000000       3.572843           0.122025
              6                0.000000       3.608932           0.045532
              7                0.000000       3.789379           0.087421
              8                0.000000       4.114182           0.123846
              9                0.000000       4.438986           0.214910
              10               0.000000       4.619433           0.234944
              11               0.000000       4.727701           0.677512
              12               0.000000       4.150272           0.351505
              13               0.000000       3.825468           0.231301
              14               0.000000       4.078093           0.338756
              15               0.000000       4.114182           0.240407
              16               0.000000       4.547254           0.203982
              17               0.000000       4.475076           0.429819
              18               0.000000       4.438986           0.404321
              19               0.000000       4.294629           0.222195
              20               0.000000       3.861557           0.437104
...                                 ...            ...                ...
38     126699 24               0.000000       1.587930           0.156629
              25               0.000000       1.479662           0.041889
              26               0.000000       0.216536           0.050996
              27               0.011583       0.036089           0.000000
       126817 5                0.000000       0.577429           0.103812
              12               0.000000       0.469161           0.145701
              19               0.000000       0.396983           0.109276
       127120 2                0.000000       0.180447           0.012749
              3                0.000000       0.324804           0.018213
              4                0.000000       0.396983           0.025498
              5                0.000000       0.180447           0.005464
              8                0.000000       0.252625           0.007285
              9                0.000000       0.180447           0.003643
              14               0.000000       0.252625           0.092885
              15               0.000000       0.252625           0.010928
              16               0.000000       0.288715           0.047353
              17               0.000000       0.360893           0.040068
              18               0.000000       0.433072           0.020034
              19               0.000000       0.252625           0.009106
              20               0.000000       0.180447           0.000000
              23               0.000000       0.396983           0.224016
              24               0.000000       0.469161           0.236765
              25               0.000000       0.433072           0.021855
              26               0.000000       0.324804           0.020034
              28               0.000000       0.324804           0.007285
       127560 1                0.000000       0.396983           0.049174
              3                0.000000       0.469161           0.185769
              7                0.000000       0.324804           0.056459
              11               0.000000       0.288715           0.125667
              12               0.000000       0.613518           0.741256
              25               0.000000       0.324804           0.209446
       127648 6                0.000000       0.144357           0.027319
              7                0.000000       0.324804           0.056459
              9                0.000000       0.324804           0.010928
              11               0.000000       0.288715           0.125667
              22               0.000579       0.036089           0.000000
       128817 12               0.000000       0.180447           0.030962
              19               0.000000       0.288715           0.034604
              26               0.000000       0.216536           0.005464
       129429 12               0.000000       0.649608           0.087421
              26               0.000000       0.577429           0.267726
       129629 19               0.000000       0.757876           1.934186
       129716 5                0.000000       0.433072           0.517240
              12               0.000000       0.360893           0.442568
              19               0.000000       0.613518           0.999876
       129982 19               0.000000       0.613518           0.318722
       130027 12               0.000000       0.685697           0.806822
       130434 1                0.000000       0.396983           0.049174
              2                0.000000       0.324804           0.040068
              3                0.000000       0.469161           0.185769

                   random_attacker_cnt  random_defender_cnt  same_pledge_cnt  \
server acc_id day
0      75     8               2.549816             0.429188         1.591434
              15              0.000000             0.071531         0.000000
              16              0.451866             0.214594         0.000000
              17              0.000000             0.429188         0.000000
              18              0.451866             0.357657         0.000000
              19              3.292167             0.143063         0.000000
              20              0.000000             0.071531         0.000000
              21              1.065113             0.071531         0.000000
              22              0.000000             0.000000         0.000000
              23              0.000000             0.071531         0.000000
              24              0.000000             0.071531         0.000000
              25              0.484142             0.357657         0.000000
              26              0.968284             0.929907         0.000000
              27              0.839180             0.643782         0.000000
              28              0.000000             1.144501         0.000000
       161    4               0.000000             0.000000         0.000000
              18              0.000000             0.000000         0.000000
       260    8               0.000000             0.000000         0.000000
              9               0.000000             0.000000         0.000000
              10              0.000000             0.000000         0.000000
              11              0.000000             0.000000         0.000000
              12              0.000000             0.000000         0.000000
              13              0.000000             0.000000         0.000000
              15              0.000000             0.000000         0.000000
              16              0.000000             0.071531         0.000000
              17              0.000000             0.000000         0.000000
              21              0.000000             0.000000         0.000000
              23              0.000000             0.000000         0.000000
              27              0.000000             0.000000         0.000000
              28              0.000000             0.000000         0.000000
       309    1               0.839180             0.715313         1.591434
              2               6.648887             1.430627         0.000000
              3               4.099071             0.929907         0.795717
              4               3.259891             0.929907         0.795717
              5               0.742351             0.357657         8.752889
              6               0.000000             1.144501         0.000000
              7               9.101874             0.429188         0.000000
              8               0.000000             0.500719         0.000000
              9              10.328368             0.500719         1.193576
              10              3.292167             1.287564         4.774303
              11              4.260452             1.001439         1.591434
              12              0.774628             0.286125         4.774303
              13             16.041246             0.572251         4.774303
              14              6.422954             0.858376         0.795717
              15              9.392360             1.430627         7.161455
              16              4.325004             0.929907         2.387152
              17              4.744594             0.357657         0.000000
              18              1.742912             0.929907         0.000000
              19              2.711197             0.143063        12.731475
              20              2.323883             0.929907         0.000000
...                                ...                  ...              ...
38     126699 24              0.000000             0.000000         0.000000
              25              0.000000             0.000000         0.000000
              26              0.000000             0.000000         0.000000
              27              0.000000             0.000000         0.000000
       126817 5               0.000000             0.000000         0.000000
              12              0.000000             0.000000         0.000000
              19              0.000000             0.000000         0.000000
       127120 2               0.000000             0.000000         0.000000
              3               0.000000             0.000000         0.000000
              4               0.000000             0.000000         0.000000
              5               0.000000             0.000000         0.000000
              8               0.000000             0.000000         0.000000
              9               0.000000             0.000000         0.000000
              14              0.000000             0.572251         0.000000
              15              0.000000             0.000000         0.000000
              16              0.000000             0.000000         0.000000
              17              0.000000             0.000000         0.000000
              18              0.000000             0.000000         0.000000
              19              0.000000             0.214594         0.000000
              20              0.000000             0.357657         0.795717
              23              0.000000             0.000000         0.000000
              24              0.000000             0.000000         0.000000
              25              0.000000             0.000000         0.000000
              26              0.000000             0.000000         0.000000
              28              0.000000             0.357657         0.000000

In [76]:
# Change name of the columns which are same with the ones in combat file
rename_dict = {"etc_cnt" : "p_etc_cnt", "random_attacker_cnt" : "p_random_attacker_cnt",
              'same_pledge_cnt' : 'p_same_pledge_cnt', "temp_cnt" : "p_temp_cnt", 
               "random_defender_cnt" : "p_random_defender_cnt"}
pledge.rename(columns=rename_dict, inplace=True)

In [77]:
pledge.head(20)

                   combat_char_cnt  combat_play_time  p_etc_cnt  \
server acc_id day
0      75     8           1.190948          1.883065   0.332678
              15          0.505250          0.451973   0.276052
              16          0.288715          0.404134   0.063704
              17          0.721786          0.902671   0.254818
              18          0.902233          0.979004   0.325600
              19          0.613518          1.014680   0.233583
              20          0.288715          0.473981   0.155722
              21          0.433072          0.629889   0.375148
              22          0.505250          0.706801   0.198191
              23          0.433072          0.526336   0.247739
              24          0.396983          0.498884   0.084939
              25          0.721786          0.869891   0.148644
              26          0.974412          1.030433   0.686592
              27          0.613518          1.163407   0.396383
              28          0.685697          1.124835   0.587496
       161    4           0.000000          0.000000   0.000000
              18          0.000000          0.000000   0.000000
       260    8           0.000000          0.000000   0.000000
              9           0.000000          0.000000   0.000000
              10          0.000000          0.000000   0.000000

                   non_combat_play_time  play_char_cnt  pledge_combat_cnt  \
server acc_id day
0      75     8                0.000000       4.402897           0.043710
              15               0.000000       1.118769           0.000000
              16               0.000000       1.190948           0.020034
              17               0.000000       2.165359           0.000000
              18               0.000000       2.345806           0.018213
              19               0.000000       2.417984           0.000000
              20               0.000000       1.732287           0.000000
              21               0.000000       2.273627           0.000000
              22               0.000000       2.021002           0.000000
              23               0.000000       2.129270           0.000000
              24               0.000000       1.912734           0.000000
              25               0.000000       2.742788           0.000000
              26               0.000000       2.417984           0.003643
              27               0.000000       2.562342           0.000000
              28               0.000000       2.165359           0.000000
       161    4                0.012278       0.144357           0.000000
              18               0.009614       0.216536           0.000000
       260    8                0.007992       0.108268           0.000000
              9                0.008687       0.144357           0.000000
              10               0.040657       0.360893           0.000000

                   p_random_attacker_cnt  p_random_defender_cnt  \
server acc_id day
0      75     8                 2.549816               0.429188
              15                0.000000               0.071531
              16                0.451866               0.214594
              17                0.000000               0.429188
              18                0.451866               0.357657
              19                3.292167               0.143063
              20                0.000000               0.071531
              21                1.065113               0.071531
              22                0.000000               0.000000
              23                0.000000               0.071531
              24                0.000000               0.071531
              25                0.484142               0.357657
              26                0.968284               0.929907
              27                0.839180               0.643782
              28                0.000000               1.144501
       161    4                 0.000000               0.000000
              18                0.000000               0.000000
       260    8                 0.000000               0.000000
              9                 0.000000               0.000000
              10                0.000000               0.000000

                   p_same_pledge_cnt  p_temp_cnt
server acc_id day
0      75     8             1.591434    1.977661
              15            0.000000    1.582129
              16            0.000000    0.791064
              17            0.000000    1.681012
              18            0.000000    2.373193
              19            0.000000    2.175427
              20            0.000000    0.494415
              21            0.000000    0.395532
              22            0.000000    1.384363
              23            0.000000    1.087714
              24            0.000000    1.087714
              25            0.000000    1.779895
              26            0.000000    1.483246
              27            0.000000    0.197766
              28            0.000000    0.692181
       161    4             0.000000    0.000000
              18            0.000000    0.000000
       260    8             0.000000    0.000000
              9             0.000000    0.000000
              10            0.000000    0.000000

## Activity

In [78]:
# Remove "char_id"
activity.drop("char_id", axis=1, inplace=True)

In [79]:
activity.head()

,day,acc_id,server,playtime,npc_kill,solo_exp,party_exp,quest_exp,boss_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
0,1,75001,0,1.459994,0.000000,0.000000,0.000000,0.000000,0,0.00000,0.000000,0.0,0.0,1.119053,0.033934,0.0
1,1,75001,0,0.286785,2.244221,0.046989,0.000000,0.000000,0,0.00000,0.000000,0.0,0.0,0.000000,-0.013933,0.0
2,1,75711,0,1.049964,2.951697,0.321164,0.166247,0.003463,1,0.24537,0.246819,0.0,0.0,0.000000,-0.001983,0.0
3,1,72230,0,0.232272,4.035346,0.098944,0.000000,0.001732,0,0.00000,0.000000,0.0,0.0,0.000000,-0.028823,0.0
4,1,34253,0,1.102106,0.595805,0.003371,0.000000,0.000000,0,0.00000,0.000000,0.0,0.0,0.000000,0.011752,0.0

In [80]:
# Total play time per account the whole period
total_play = activity.groupby("acc_id")["playtime"].sum()
total_play = pd.DataFrame({"total_play_time" : total_play})  # in case of mergi

In [81]:
total_play.head()

        total_play_time
acc_id
2             92.685947
5              6.193126
8             19.034441
17            28.823040
20            25.910161

In [82]:
activity[activity['acc_id']==46383].head()

,day,acc_id,server,playtime,npc_kill,solo_exp,party_exp,quest_exp,boss_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
1697,1,46383,0,0.130357,0.066463,0.039652,0.0,0.178325,0,0.0,0.0,0.0,0.000000,0.0,0.000066,0.0
31238,1,46383,17,0.381589,0.054317,0.003325,0.0,0.000000,0,0.0,0.0,0.0,0.000000,0.0,-0.002443,0.0
31239,1,46383,17,0.004740,0.000000,0.000000,0.0,0.000000,0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0
85646,2,46383,17,1.327268,1.017187,0.040819,0.0,0.006926,0,0.0,0.0,0.0,0.177759,0.0,-0.000792,0.0
85647,2,46383,17,0.011851,0.000000,0.000000,0.0,0.000000,0,0.0,0.0,0.0,0.000000,0.0,0.000261,0.0

In [83]:
pd.pivot_table(data=activity, index=["server","acc_id","day"], aggfunc='sum')

                   boss_monster     death  enchant_count  exp_recovery  \
server acc_id day
0      75     8               0  0.000000            0.0           0.0
              9               0  0.000000            0.0           0.0
              10              0  0.000000            0.0           0.0
              11              0  0.000000            0.0           0.0
              12              0  0.000000            0.0           0.0
              13              0  0.000000            0.0           0.0
              14              0  0.000000            0.0           0.0
              15              0  0.000000            0.0           0.0
              16              0  0.000000            0.0           0.0
              17              0  0.000000            0.0           0.0
              18              0  0.000000            0.0           0.0
              19              0  0.000000            0.0           0.0
              20              0  0.000000            0.0           0.0
              21              0  0.000000            0.0           0.0
              22              0  0.000000            0.0           0.0
              23              0  0.000000            0.0           0.0
              24              0  0.000000            0.0           0.0
              25              0  0.000000            0.0           0.0
              26              0  0.000000            0.0           0.0
              27              0  0.000000            0.0           0.0
              28              0  0.000000            0.0           0.0
       161    4               0  0.000000            0.0           0.0
              18              0  0.000000            0.0           0.0
       260    8               0  0.000000            0.0           0.0
              9               0  0.000000            0.0           0.0
              10              0  0.000000            0.0           0.0
              11              0  0.000000            0.0           0.0
              12              0  0.000000            0.0           0.0
              13              0  0.000000            0.0           0.0
              15              0  0.000000            0.0           0.0
              16              0  0.000000            0.0           0.0
              17              0  0.000000            0.0           0.0
              21              0  0.000000            0.0           0.0
              23              0  0.000000            0.0           0.0
              27              0  0.000000            0.0           0.0
              28              0  0.000000            0.0           0.0
       266    27              0  0.000000            0.0           0.0
              28              0  0.000000            0.0           0.0
       281    2               0  0.000000            0.0           0.0
              5               0  0.490740            0.0           0.0
              6               0  1.226849            0.0           0.0
              7               0  0.245370            0.0           0.0
              8               1  0.000000            0.0           0.0
              9               0  0.000000            0.0           0.0
              10              1  0.000000            0.0           0.0
              11              0  0.000000            0.0           0.0
              12              0  0.000000            0.0           0.0
              14              0  0.000000            0.0           0.0
              15              0  0.000000            0.0           0.0
              16              0  0.000000            0.0           0.0
...                         ...       ...            ...           ...
39     129217 1               0  0.000000            0.0           0.0
              2               0  0.245370            0.0           0.0
              3               0  0.000000            0.0           0.0
              4               0  0.000000            0.0           0.0
              5               0  0.000000            0.0           0.0
              6               0  0.000000            0.0           0.0
              8               0  0.000000            0.0           0.0
              9               0  0.000000            0.0           0.0
              10              0  0.736109            0.0           0.0
              11              0  0.490740            0.0           0.0
              13              0  0.000000            0.0           0.0
              14              0  0.000000            0.0           0.0
              15              0  0.000000            0.0           0.0
              16              0  0.000000            0.0           0.0
              17              0  0.245370            0.0           0.0
              18              0  0.000000            0.0           0.0
              19              0  0.000000            0.0           0.0
              20              0  0.000000            0.0           0.0
              21              0  0.000000            0.0           0.0
              22              0  0.245370            0.0           0.0
              23              0  0.000000            0.0           0.0
              24              0  0.490740            0.0           0.0
              25              0  0.490740            0.0           0.0
              26              0  0.245370            0.0           0.0
              27              0  0.981479            0.0           0.0
              28              0  0.000000            0.0           0.0
       129221 1               0  0.000000            0.0           0.0
              2               0  0.000000            0.0           0.0
              4               0  0.000000            0.0           0.0
              5               0  0.000000            0.0           0.0
              6               0  0.000000            0.0           0.0
              7               0  0.000000            0.0           0.0
              8               0  0.000000            0.0           0.0
              11              0  0.000000            0.0           0.0
              12              0  0.000000            0.0           0.0
              13              0  0.000000            0.0           0.0
              14              0  0.000000            0.0           0.0
              15              0  0.000000            0.0           0.0
              16              0  0.000000            0.0           0.0
              19              0  0.000000            0.0           0.0
              20              0  0.000000            0.0           0.0
              21              0  0.000000            0.0           0.0
              22              0  0.000000            0.0           0.0
              23              0  0.000000            0.0           0.0
              24              0  0.000000            0.0           0.0
              25              0  0.000000            0.0           0.0
              26              0  0.000000            0.0           0.0
              28              0  0.000000            0.0           0.0
       129675 6               0  0.000000            0.0           0.0
              7               0  0.000000            0.0           0.0

                    fishing  game_money_change  npc_kill  party_exp  playtime  \
server acc_id day
0      75     8    0.177720          -0.000456  0.000000   0.000000  0.196720
              9    0.177759          -0.000145  0.000000   0.000000  0.222791
              10   0.088880          -0.000145  0.000000   0.000000  0.154058
              11   0.088840          -0.000145  0.000000   0.000000  0.158798
              12   0.088840          -0.000145  0.000000   0.000000  0.151688
              13   0.088840          -0.002135  0.000000   0.000000  0.199090
              14   0.088840          -0.000145  0.000000   0.000000  0.154058
              15   0.177720          -0.000600  0.003374   0.000000  0.241752
              16   0.177759           0.001159  0.000000   0.000000  0.225161
              17   0.177759          -0.001490  0.000000   0.000000  0.367369
              18   0.177759           0.000260  0.021255   0.000000  0.291525
              19   0.177759           0.000490  0.012483   0.000000  0.315226
              20   0.133319          -0.000258  0.000000   0.000000  0.154058
              21   0.222199          -0.000689  0.000000   0.000000  0.253603
              22   0.177759           0.000747  0.000337   0.000000  0.241752
              23   0.000000          -0.000863  0.146758   0.000000  0.175389
              24   0.000000           0.001094  0.186231   0.000000  0.203830
              25   0.143116          -0.000921  0.205799   0.000000  0.414771
              26   0.000000           0.001174  0.196015   0.000000  0.241752
              27   0.000000          -0.000901  0.129552   0.000000  0.163538
              28   0.000000          -0.000323  0.130227   0.000000  0.187240
       161    4    0.000000          -0.000003  0.000000   0.000000  0.009480
              18   0.000000          -0.011405  0.000000   0.000000  0.118506
       260    8    0.000000          -0.162044  0.023954   0.000000  0.056883
              9    0.000000           0.012375  0.000000   0.000000  0.009480
              10   0.334385          -0.005202  0.032388   0.003588  0.395810
              11   0.000000          -0.000142  0.000000   0.000000  0.002370
              12   0.000000          -0.003019  0.000000   0.000000  0.004740
              13   0.000000          -0.003219  0.167338   0.000000  0.170649
              15   0.000000          -0.000329  0.117069   0.016743  0.151688
              16   0.000000           0.013849  0.015182   0.002362  0.054513
              17   0.000000           0.009197  0.131239   0.000000  0.161168
              21   0.000000          -0.023202  0.101887   0.011554  0.149318
              23   0.000000           0.000237  0.168688   0.000000  0.154058
              27   0.000000          -0.000135  0.001350   0.000000  0.040292
              28   0.000000           0.015786  0.000337   0.000000  0.042662
       266    27   0.000000           0.012780  0.254381   0.000000  0.485875
              28   0.000000           0.000000  0.000000   0.000000  0.011851
       281    2    0.000000          -0.001128  0.000000   0.000000  0.002370
              5    0.000000           0.001007  1.315764   0.000000  0.137467
              6    0.319018          -0.004048  1.431483   0.000000  0.459803
              7    0.037013           0.000518  1.568795   0.000000  0.644673
              8    0.000000           1.147846  0.027665   0.000000  0.125616
              9    0.000000          -0.921697  0.012483   0.000000  0.722887
              10   0.000000          -0.042769  0.000000   0.000000  0.400550
              11   0.000000           0.000054  0.017881   0.000000  0.028441
              12   0.000000          -0.003984  0.077596   0.000000  0.075844
              14   0.588422          -0.125929  0.000000   0.000000  1.860545
              15   0.257198           0.001773  0.159241   0.000000  0.329447
              16   0.009441          -0.042779  0.000000   0.000000  1.125807
...                     ...                ...       ...        ...       ...
39     129217 1    0.000000           0.000843  0.000000   0.000000  0.237012
              2    0.000000           0.001101  0.000000   0.000000  0.263083
              3    0.000000           0.024094  0.000000   0.000000  0.616231
              4    0.444753           0.000306  0.000000   0.000000  1.301196
              5    0.000000           0.000000  0.000000   0.000000  0.282044
              6    0.000000          -0.000354  0.000000   0.000000  0.718147
              8    0.000000          -0.002217  0.000000   0.000000  0.146947
              9    0.000000          -0.015431  0.000000   0.000000  0.139837
              10   0.000000          -0.004790  0.000000   0.000000  0.329447
              11   0.382142           0.001269  0.000000   0.000000  0.556978
              13   0.000000           0.003115  0.000000   0.000000  0.296265
              14   0.684372          -0.001094  0.000000   0.000000  1.064184
              15   0.000000          -0.000217  0.000000   0.000000  0.386330
              16   0.000000          -0.003055  0.000000   0.000000  0.500096
              17   0.598456           0.000309  0.000000   0.000000  0.796361
              18   0.202329          -0.003325  0.000000   0.000000  0.519056
              19   0.000000           0.003023  0.000000   0.000000  0.042662
              20   0.152241          -0.002680  0.000000   0.000000  0.447953
              21   0.097254           0.001441  0.000000   0.000000  0.839023
              22   0.000000           0.001155  0.000000   0.000000  0.255973
              23   0.552831           0.026162  0.000000   0.000000  0.701556
              24   0.000000          -0.023603  0.000000   0.000000  0.727627
              25   0.000000           0.000207  0.000000   0.000000  1.014412
              26   0.000000           0.006611  0.000000   0.000000  0.561719
              27   0.000000           0.008493  0.000000   0.000000  1.232463
              28   0.000000           0.004573  0.000000   0.000000  0.175389
       129221 1    0.000000          -0.000871  0.000000   0.000000  0.007110
              2    0.000000          -0.000871  0.000000   0.000000  0.004740
              4    0.000000           0.004414  0.000000   0.000000  0.054513
              5    0.000000          -0.001263  0.000000   0.000000  0.049773
              6    0.000000          -0.000857  0.000000   0.000000  0.011851
              7    0.000000          -0.001143  0.000000   0.000000  0.007110
              8    0.000000          -0.001143  0.000000   0.000000  0.004740
              11   0.000000           0.018727  0.000000   0.000000  0.255973
              12   0.000000           0.007423  0.000000   0.000000  0.090065
              13   0.000000           0.001115  0.000000   0.000000  0.118506
              14   0.000000          -0.000956  0.000000   0.000000  0.007110
              15   0.000000          -0.001299  0.000000   0.000000  0.023701
              16   0.000000          -0.001126  0.000000   0.000000  0.018961
              19   0.000000           0.011066  0.000000   0.000000  0.061623
              20   0.942163          -0.001192  0.000000   0.000000  1.711227
              21   0.000000          -0.000871  0.000000   0.000000  0.011851
              22   0.000000          -0.000581  0.000000   0.000000  0.009480
              23   0.000000          -0.000871  0.000000   0.000000  0.007110
              24   0.000000          -0.000871  0.000000   0.000000  0.014221
              25   0.000000          -0.000871  0.000000   0.000000  0.007110
              26   0.000000          -0.000871  0.000000   0.000000  0.007110
              28   0.000000          -0.001742  0.000000   0.000000  0.011851
       129675 6    0.000000           0.000000  0.000000   0.000000  0.007110
              7    0.000000           0.000000  0.000000   0.000000  0.004740

                   private_shop  quest_exp    revive  solo_exp
server acc_id day
0      75     8             0.0   0.004329  0.000000  0.017322
              9             0.0   0.004329  0.000000  0.015449
              10            0.0   0.001732  0.000000  0.006085
              11            0.0   0.001732  0.000000  0.006262
              12            0.0   0.001732  0.000000  0.006097
              13            0.0   0.006926  0.000000  0.006258
              14            0.0   0.001732  0.000000  0.006262
              15            0.0   0.003463  0.000000  0.010111
              16            0.0   0.003463  0.000000  0.009160
              17            0.0   0.013853  0.000000  0.009414
              18            0.0   0.008658  0.000000  0.014175
              19            0.0   0.003463  0.000000  0.012149
              20            0.0   0.003463  0.000000  0.007816
              21            0.0   0.008658  0.000000  0.010917
              22            0.0   0.003463  0.000000  0.009614
              23            0.0   0.000000  0.000000  0.023424
              24            0.0   0.003463  0.000000  0.024501
              25            0.0   0.001732  0.000000  0.032832
              26            0.0   0.006926  0.000000  0.027519
              27            0.0   0.001732  0.000000  0.021672
              28            0.0   0.010389  0.000000  0.023490
       161    4             0.0   0.000000  0.000000  0.000000
              18            0.0   0.000000  0.000000  0.000000
       260    8             0.0   0.000866  0.000000  0.001511
              9             0.0   0.000866  0.000000  0.000000
              10            0.0   0.000866  0.000000  0.007626
              11            0.0   0.000866  0.000000  0.000000
              12            0.0   0.000866  0.000000  0.000000
              13            0.0   0.000866  0.000000  0.006570
              15            0.0   0.001732  0.000000  0.000075
              16            0.0   0.001732  0.000000  0.000249
              17            0.0   0.001732  0.000000  0.004961
              21            0.0   0.001732  0.000000  0.001499
              23            0.0   0.000866  0.000000  0.004073
              27            0.0   0.000000  0.000000  0.000057
              28            0.0   0.000000  0.000000  0.000000
       266    27            0.0  17.389637  0.000000  3.519318
              28            0.0   0.000000  0.000000  0.000000
       281    2             0.0   0.000000  0.000000  0.000000
              5             0.0   0.000000  0.493639  0.020480
              6             0.0   0.003463  1.234097  0.024586
              7             0.0   0.002597  0.246819  0.027520
              8             0.0   0.000866  0.000000  0.001528
              9             0.0   0.000866  0.000000  0.000731
              10            0.0   0.000866  0.000000  0.000000
              11            0.0   0.000866  0.000000  0.000916
              12            0.0   0.000866  0.000000  0.004531
              14            0.0   0.001732  0.000000  0.012397
              15            0.0   0.001732  0.000000  0.009930
              16            0.0   0.001732  0.000000  0.000193
...                         ...        ...       ...       ...
39     129217 1             0.0   3.373672  0.000000  0.000000
              2             0.0  12.627015  0.246819  0.000000
              3             0.0   0.789608  0.000000  0.000000
              4             0.0   0.409289  0.000000  0.000000
              5             0.0   0.000000  0.000000  0.000000
              6             0.0   0.332468  0.000000  0.000000
              8             0.0   0.332468  0.000000  0.000000
              9             0.0   0.262620  0.000000  0.000000
              10            0.0   0.526405  0.740458  0.000000
              11            0.0   0.166234  0.493639  0.000000
              13            0.0   0.283982  0.000000  0.000000
              14            0.0   0.055411  0.000000  0.000000
              15            0.0   0.429436  0.000000  0.000000
              16            0.0   0.467847  0.000000  0.000000
              17            0.0   0.041559  0.246819  0.000000
              18            0.0   0.166233  0.000000  0.000000
              19            0.0   0.027706  0.000000  0.000000
              20            0.0   0.027706  0.000000  0.000000
              21            0.0   0.232033  0.000000  0.000000
              22            0.0   0.027706  0.246819  0.000000
              23            0.0   0.000000  0.000000  0.000000
              24            0.0   0.135064  0.493639  0.000000
              25            0.0   0.000000  0.493639  0.000000

In [88]:
pd.pivot_table(data=activity.drop("server", axis=1),\
               index=["acc_id", "day"], aggfunc=sum).head()

            boss_monster  death  enchant_count  exp_recovery  fishing  \
acc_id day
2      1               0    0.0            0.0           0.0      0.0
       2               0    0.0            0.0           0.0      0.0
       3               0    0.0            0.0           0.0      0.0
       4               0    0.0            0.0           0.0      0.0
       5               0    0.0            0.0           0.0      0.0

            game_money_change  npc_kill  party_exp  playtime  private_shop  \
acc_id day
2      1             1.022652       0.0        0.0  2.737490      2.493091
       2            -1.042002       0.0        0.0  3.405864      3.188761
       3             0.450366       0.0        0.0  3.412974      3.223522
       4            -0.007215       0.0        0.0  3.412974      3.171419
       5             0.015365       0.0        0.0  3.412974      3.175172

            quest_exp  revive  solo_exp
acc_id day
2      1          0.0     0.0       0.0
       2          0.0     0.0       0.0
       3          0.0     0.0       0.0
       4          0.0     0.0       0.0
       5          0.0     0.0       0.0

In [89]:
pd.pivot_table(data=activity, index=["acc_id", "day"], values=["server"]).head()

            server
acc_id day
2      1      20.0
       2      20.0
       3      20.0
       4      20.0
       5      20.0

In [94]:
# Sum all the values per day for each account
activity = pd.concat([pd.pivot_table(data=activity.drop("server", axis=1),\
                                     index=["acc_id", "day"], aggfunc=sum),
                     pd.pivot_table(data=activity, index=["acc_id", "day"], values=["server"])],
                    axis=1)

# Total exp
activity["total_exp"] = activity["solo_exp"] + activity["party_exp"] + activity["quest_exp"]

# How long do users spend time fishing?
activity["fishing_prop"] = activity["fishing"] / activity["playtime"]

activity

            boss_monster      death  enchant_count  exp_recovery   fishing  \
acc_id day
2      1               0   0.000000            0.0           0.0  0.000000
       2               0   0.000000            0.0           0.0  0.000000
       3               0   0.000000            0.0           0.0  0.000000
       4               0   0.000000            0.0           0.0  0.000000
       5               0   0.000000            0.0           0.0  0.000000
       6               0   0.000000            0.0           0.0  0.000000
       7               0   0.000000            0.0           0.0  0.000000
       8               0   0.000000            0.0           0.0  0.000000
       9               0   0.000000            0.0           0.0  0.000000
       10              0   0.000000            0.0           0.0  0.000000
       11              0   0.000000            0.0           0.0  0.000000
       12              0   0.000000            0.0           0.0  0.000000
       13              0   0.000000            0.0           0.0  0.000000
       14              0   0.000000            0.0           0.0  0.000000
       15              0   0.000000            0.0           0.0  0.000000
       16              0   0.000000            0.0           0.0  0.000000
       17              0   0.000000            0.0           0.0  0.000000
       18              0   0.000000            0.0           0.0  0.000000
       19              0   0.000000            0.0           0.0  0.000000
       20              0   0.000000            0.0           0.0  0.000000
       21              0   0.000000            0.0           0.0  0.000000
       22              0   0.000000            0.0           0.0  0.000000
       23              0   0.000000            0.0           0.0  0.000000
       24              0   0.000000            0.0           0.0  0.000000
       25              0   0.000000            0.0           0.0  0.000000
       26              0   0.000000            0.0           0.0  0.000000
       27              0   0.000000            0.0           0.0  0.000000
       28              0   0.000000            0.0           0.0  0.000000
5      9               1   0.000000            0.0           0.0  0.000000
       14              1   0.000000            0.0           0.0  0.000000
       20              1   0.000000            0.0           0.0  0.000000
       22              1   0.000000            0.0           0.0  0.000000
       23              1   0.000000            0.0           0.0  0.021292
       24              1   0.000000            0.0           0.0  0.000000
       25              1   0.000000            0.0           0.0  0.000000
       26              1   0.245370            0.0           0.0  0.375032
       27              1   0.000000            0.0           0.0  0.000000
       28              0   0.000000            0.0           0.0  0.000000
8      1               0   0.000000            0.0           0.0  0.000000
       2               0   0.000000            0.0           0.0  0.000000
       3               0   0.000000            0.0           0.0  0.533277
       4               0   0.000000            0.0           0.0  0.000000
       5               1   3.435177            0.0           0.0  0.622157
       6               0  85.143314            0.0           0.0  0.000000
       7               0   0.000000            0.0           0.0  0.000000
       8               0   0.000000            0.0           0.0  0.533277
       9               0   0.000000            0.0           0.0  0.000000
       10              0   0.000000            0.0           0.0  0.610543
       11              0   0.000000            0.0           0.0  0.000000
       12              0   0.000000            0.0           0.0  0.262570
...                  ...        ...            ...           ...       ...
130470 5               0   0.000000            0.0           0.0  0.000000
       6               0   0.000000            0.0           0.0  0.002094
       7               0   0.000000            0.0           0.0  0.000000
       9               0   0.000000            0.0           0.0  0.000000
       10              0   0.000000            0.0           0.0  0.000000
       11              0   0.245370            0.0           0.0  0.000000
       12              0   0.000000            0.0           0.0  0.000000
       13              0   0.000000            0.0           0.0  0.000000
       14              0   0.000000            0.0           0.0  0.000000
       15              0   0.000000            0.0           0.0  0.000000
       16              0   0.000000            0.0           0.0  0.000000
       17              1   0.000000            0.0           0.0  0.000000
       18              0   0.000000            0.0           0.0  0.115543
       19              0   0.000000            0.0           0.0  0.000000
       20              0   0.000000            0.0           0.0  0.000000
       21              0   0.490740            0.0           0.0  0.000000
       22              1   0.000000            0.0           0.0  0.000000
       24              0   0.000000            0.0           0.0  0.000000
       25              0   0.000000            0.0           0.0  0.025716
       26              0   0.000000            0.0           0.0  0.007071
       27              0   0.000000            0.0           0.0  0.000000
       28              0   0.000000            0.0           0.0  0.000000
130473 1               0   0.000000            0.0           0.0  1.322962
       2               0   0.000000            0.0           0.0  2.348790
       3               1   0.245370            0.0           0.0  2.226531
       4               0   0.490740            0.0           0.0  0.124194
       5               1   0.981479            0.0           0.0  2.265441
       6               1   0.000000            0.0           0.0  2.724098
       7               1   0.245370            0.0           0.0  2.261451
       8               0   0.000000            0.0           0.0  1.364084
       9               0   1.962958            0.0           0.0  0.000000
       10              1   0.245370            0.0           0.0  1.509332
       11              0   0.000000            0.0           0.0  1.624402
       12              0   0.000000            0.0           0.0  3.409261
       13              0   0.000000            0.0           0.0  2.713591
       14              0   0.000000            0.0           0.0  2.294830
       15              1   0.000000            0.0           0.0  0.000000
       16              0   0.245370            0.0           0.0  0.000000
       17              0   0.000000            0.0           0.0  1.725053
       18              0   0.000000            0.0           0.0  0.000000
       19              0   0.000000            0.0           0.0  1.877452
       20              1   0.245370            0.0           0.0  2.211955
       21              0   0.000000            0.0           0.0  1.343859
       22              0   0.000000            0.0           0.0  0.000000
       23              0   0.000000            0.0           0.0  0.472484
       24              0   0.000000            0.0           0.0  2.911180
       25              1   0.000000            0.0           0.0  2.170083
       26              0   0.981479            0.0           0.0  0.853283
       27              0   0.000000            0.0           0.0  3.012147
       28              0   0.000000            0.0           0.0  2.711813

            fishing_prop  game_money_change  npc_kill     party_exp  playtime  \
acc_id day
2      1        0.000000           1.022652  0.000000  0.000000e+00  2.737490
       2        0.000000          -1.042002  0.000000  0.000000e+00  3.405864
       3        0.000000           0.450366  0.000000  0.000000e+00  3.412974
       4        0.000000          -0.007215  0.000000  0.000000e+00  3.412974
       5        0.000000           0.015365  0.000000  0.000000e+00  3.412974
       6        0.000000          -0.003792  0.000000  0.000000e+00  3.412974
       7        0.000000          -0.363492  0.000000  0.000000e+00  3.412974
       8        0.000000          -0.006605  0.000000  0.000000e+00  2.803853
       9        0.000000          -0.010956  0.000000  0.000000e+00  3.403494
       10       0.000000          -0.182357  0.000000  0.000000e+00  3.412974
       11       0.000000          -0.022643  0.000000  0.000000e+00  3.412974
       12       0.000000          -0.091739  0.000000  0.000000e+00  3.412974
       13       0.000000          -0.007243  0.000000  0.000000e+00  3.412974
       14       0.000000           0.043786  0.000000  0.000000e+00  3.410604
       15       0.000000          -0.006308  0.000000  0.000000e+00  2.659276
       16       0.000000          -0.005288  0.000000  0.000000e+00  3.220994
       17       0.000000          -0.007158  0.000000  0.000000e+00  3.412974
       18       0.000000           0.005761  0.000000  0.000000e+00  3.412974
       19       0.000000           0.019190  0.000000  0.000000e+00  3.412974
       20       0.000000          -0.063430  0.000000  0.000000e+00  3.412974
       21       0.000000          -0.006988  0.000000  0.000000e+00  3.412974
       22       0.000000          -0.007257  0.000000  0.000000e+00  3.412974
       23       0.000000          -0.106340  0.000000  0.000000e+00  2.784892
       24       0.000000           0.407511  0.000000  0.000000e+00  3.412974
       25       0.000000          -0.034699  0.000000  0.000000e+00  3.412974
       26       0.000000          -0.036085  0.000000  0.000000e+00  3.412974
       27       0.000000           0.054837  0.000000  0.000000e+00  3.412974
       28       0.000000          -0.016598  0.000000  0.000000e+00  3.412974
5      9        0.000000           0.005400  0.157892  0.000000e+00  0.381589
       14       0.000000           0.004489  0.151819  0.000000e+00  0.215681
       20       0.000000           0.011763  0.162615  0.000000e+00  0.215681
       22       0.000000          -0.084160  0.522257  0.000000e+00  1.052334
       23       0.034685           0.008311  0.359642  0.000000e+00  0.613861
       24       0.000000           0.016587  0.320169  5.832353e-01  0.860354
       25       0.000000           0.011216  0.432178  1.106078e-01  0.687335
       26       0.454693           0.166371  0.337713  0.000000e+00  0.824802
       27       0.000000           0.012392  0.511124  0.000000e+00  0.746588
       28       0.000000          -0.007529  0.275636  0.000000e+00  0.594900
8      1        0.000000           0.731042  3.089008  0.000000e+00  0.469284
       2        0.000000          -0.189372  4.762727  0.000000e+00  0.564089
       3        0.445545          -0.526114  2.288079  0.000000e+00  1.196911
       4        0.000000           0.012228  3.610253  0.000000e+00  0.353148
       5        0.420673          -0.006914  4.304572  0.000000e+00  1.478955
       6        0.000000           3.294432  4.043780  0.000000e+00  0.464544
       7        0.000000          -3.291957  4.664888  0.000000e+00  0.523797
       8        0.745033          -0.018404  0.085693  0.000000e+00  0.715777
       9        0.000000          -0.000456  0.000000  0.000000e+00  0.120876
       10       0.771257           0.003227  0.103574  0.000000e+00  0.791620
       11       0.000000          -0.001853  0.076247  0.000000e+00  0.125616
       12       0.139175           0.005237  0.809363  0.000000e+00  1.886616
...                  ...                ...       ...           ...       ...
130470 5        0.000000           0.017636  0.468952  0.000000e+00  0.661264
       6        0.003078          -0.016545  1.197682  0.000000e+00  0.680225
       7        0.000000          -0.001748  0.754709  0.000000e+00  0.990711
       9        0.000000           0.000016  0.684535  2.659239e-04  0.820062
       10       0.000000           0.015825  0.569490  1.176439e-02  0.760809
       11       0.000000          -0.011552  0.587370  0.000000e+00  0.651783
       12       0.000000           0.009130  0.719622  0.000000e+00  0.850873
       13       0.000000          -0.002412  0.649785  0.000000e+00  0.857984
       14       0.000000          -0.002943  0.637977  0.000000e+00  0.841393
       15       0.000000           0.011698  0.495942  0.000000e+00  0.803471
       16       0.000000          -0.012714  0.772927  3.822620e-02  0.919607
       17       0.000000          -0.002065  0.744250  9.783302e-04  1.004931
       18       0.083619           0.005830  1.093433  1.606635e-02  1.381780
       19       0.000000           0.004399  0.891683  0.000000e+00  1.187431
       20       0.000000          -0.012763  0.794181  0.000000e+00  1.106846
       21       0.000000          -0.001925  0.735816  0.000000e+00  1.054704
       22       0.000000           0.012255  1.043164  0.000000e+00  1.177950
       24       0.000000          -0.007282  0.976702  0.000000e+00  1.125807
       25       0.029245           0.031589  0.734803  0.000000e+00  0.879315
       26       0.008775          -0.034725  0.702078  0.000000e+00  0.805841
       27       0.000000           0.036247  0.811050  0.000000e+00  0.891165
       28       0.000000          -0.035967  0.604577  0.000000e+00  0.770289
130473 1        0.562685          -0.073805  4.220228  0.000000e+00  2.351160
       2        0.840543          -0.042648  4.402410  0.000000e+00  2.794373
       3        0.761278          -0.108243  2.323166  1.848831e-03  2.924729
       4        0.036746          -0.137576  4.167935  2.791218e-04  3.379792
       5        0.719754          -0.059555  4.493164  2.078811e-03  3.147521
       6        0.893740          -0.145509  3.068091  6.486633e-05  3.047975
       7        0.846628          -0.036404  3.864634  2.297840e-03  2.671126
       8        0.690916          -0.113852  0.000000  0.000000e+00  1.974311
       9        0.000000          -0.068439  0.000000  5.616132e-07  2.965021
       10       0.616473          -0.260606  0.096827  1.223474e-03  2.448335
       11       0.787778           0.006057  0.181845  7.682869e-04  2.062005
       12       0.998912          -0.056841  0.000000  0.000000e+00  3.412974
       13       0.997314          -0.056852  0.000000  0.000000e+00  2.720899
       14       0.672852           0.004789  0.170037  0.000000e+00  3.410604
       15       0.000000          -0.905680  0.069499  0.000000e+00  2.808593
       16       0.000000          -0.121711  0.060390  0.000000e+00  2.130739
       17       0.875852           0.043559  0.042847  0.000000e+00  1.969570
       18       0.000000           0.686506  0.042172  0.000000e+00  0.336557
       19       0.741004          -0.679442  0.162278  8.811711e-04  2.533659
       20       0.650360           0.216732  0.191967  1.990919e-04  3.401123
       21       0.415081           0.580611  0.046895  9.041973e-05  3.237585
       22       0.000000          -0.749306  0.061740  5.958716e-04  0.865094
       23       0.289753           0.162006  0.441624  7.733414e-04  1.630643
       24       0.863772          -0.063991  0.421382  0.000000e+00  3.370312
       25       0.636275          -0.068334  0.364028  1.227125e-04  3.410604
       26       0.474330          -0.043263  0.398440  1.631486e-04  1.798922
       27       0.927652           0.020019  0.278335  0.000000e+00  3.247066
       28       0.794560          -0.057011  0.303638  0.000000e+00  3.412974

            private_shop  quest_exp     revive  solo_exp  total_exp  server
acc_id day
2      1        2.493091   0.000000   0.000000  0.000000   0.000000    20.0
       2        3.188761   0.000000   0.000000  0.000000   0.000000    20.0
       3        3.223522   0.000000   0.000000  0.000000   0.000000    20.0
       4        3.171419   0.000000   0.000000  0.000000   0.000000    20.0
       5        3.175172   0.000000   0.000000  0.000000   0.000000    20.0
       6        3.174421   0.000000   0.000000  0.000000   0.000000    20.0
       7        3.174698   0.000000   0.000000  0.000000   0.000000    20.0
       8        2.576400   0.000000   0.000000  0.000000   0.000000    20.0
       9        3.110744   0.000000   0.000000  0.000000   0.000000    20.0
       10       3.184771   0.000000   0.000000  0.000000   0.000000    20.0
       11       3.176278   0.000000   0.000000  0.000000   0.000000    20.0
       12       3.175725   0.000000   0.000000  0.000000   0.000000    20.0
       13       3.175764   0.000000   0.000000  0.000000   0.000000    20.0
       14       3.157870   0.000000   0.000000  0.000000   0.000000    20.0
       15       2.412230   0.000000   0.000000  0.000000   0.000000    20.0
       16       2.996425   0.000000   0.000000  0.000000   0.000000    20.0
       17       3.176278   0.000000   0.000000  0.000000   0.000000    20.0
       18       3.172604   0.000000   0.000000  0.000000   0.000000    20.0
       19       3.172170   0.000000   0.000000  0.000000   0.000000    20.0
       20       3.175251   0.000000   0.000000  0.000000   0.000000    20.0
       21       3.100908   0.000000   0.000000  0.000000   0.000000    20.0
       22       3.176278   0.000000   0.000000  0.000000   0.000000    20.0
       23       2.561390   0.000000   0.000000  0.000000   0.000000    20.0
       24       3.175448   0.000000   0.000000  0.000000   0.000000    20.0
       25       3.169918   0.000000   0.000000  0.000000   0.000000    20.0
       26       3.174935   0.000000   0.000000  0.000000   0.000000    20.0
       27       3.173078   0.000000   0.000000  0.000000   0.000000    20.0
       28       3.169207   0.000000   0.000000  0.000000   0.000000    20.0
5      9        0.000000   0.000000   0.000000  0.162002   0.162002    16.0
       14       0.000000   0.000000   0.000000  0.196561   0.196561    16.0
       20       0.000000   0.000000   0.000000  0.208358   0.208358    16.0
       22       0.000000   0.020779   0.000000  0.625762   0.646541    16.0
       23       0.000000   0.069264   0.000000  0.245180   0.314444    16.0
       24       0.000000   0.006926   0.000000  0.142143   0.732304    16.0
       25       0.000000   0.003463   0.000000  0.243138   0.357209    16.0
       26       0.000000   0.003463   0.246819  0.114512   0.117976    16.0
       27       0.000000   0.003463   0.000000  0.135096   0.138560    16.0
       28       0.000000   0.003463   0.000000  0.078281   0.081744    16.0
8      1        0.000000   0.374342   0.000000  8.586580   8.960922    14.0
       2        0.000000   0.006926   0.000000  3.790739   3.797665    14.0
       3        0.000000   0.173161   0.000000  1.290358   1.463519    14.0
       4        0.000000   0.027706   0.000000  3.940923   3.968629    14.0
       5        0.000000   0.027706   3.455470  4.950333   4.978038    14.0
       6        0.000000   0.035400  85.646301  3.648845   3.684245    14.0
       7        0.000000   0.003463   0.000000  2.454442   2.457905    14.0
       8        0.000000   0.003463   0.000000  0.087260   0.090723    14.0
       9        0.000000   0.001732   0.000000  0.005597   0.007328    14.0
       10       0.000000   0.003463   0.000000  0.042355   0.045818    14.0
       11       0.000000   0.001732   0.000000  0.010801   0.012533    14.0
       12       0.000000   0.387879   0.000000  0.764165   1.152044    14.0
...                  ...        ...        ...       ...        ...     ...
130470 5        0.000000   0.013853   0.000000  0.102662   0.116515     7.0
       6        0.000000   0.013853   0.000000  0.566170   0.580023     7.0
       7        0.000000   0.000000   0.000000  0.273996   0.273996     7.0
       9        0.000000   0.001732   0.000000  0.028675   0.030672     7.0
       10       0.000000   0.004112   0.000000  0.016372   0.032249     7.0

In [95]:
activity.columns

Index(['boss_monster', 'death', 'enchant_count', 'exp_recovery', 'fishing',
       'fishing_prop', 'game_money_change', 'npc_kill', 'party_exp',
       'playtime', 'private_shop', 'quest_exp', 'revive', 'solo_exp',
       'total_exp', 'server'],
      dtype='object')

## Combat

In [96]:
combat[combat['acc_id']==46383].head()

,day,acc_id,char_id,server,class,level,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent
1303341,1,46383,161773,0,1,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1303342,1,46383,119714,17,3,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1303343,1,46383,210718,17,0,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1308243,2,46383,96109,17,2,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1308244,2,46383,119714,17,3,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [97]:
# Remove "char_id", "class", "server"
# '클리스도 일단 안 날리는게 좋지 않을까?'
combat.drop(["char_id"], axis=1, inplace=True)

combat.head()

,day,acc_id,server,class,level,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent
0,1,13809,15,2,13,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
1,1,13809,15,2,13,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
2,1,13809,15,3,14,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
3,1,13809,15,7,16,0.0,0.0,0.0,0.0,0.0,0.112612,0.098129
4,1,13809,15,2,11,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000

In [98]:
# Max level? or Mean level?
max_level = combat.groupby(["server","acc_id"])["level"].max()
mean_level = combat.groupby(["server","acc_id"])["level"].mean()
combat.drop("level", axis=1, inplace=True)
combat.head(10)

,day,acc_id,server,class,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent
0,1,13809,15,2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
1,1,13809,15,2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
2,1,13809,15,3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
3,1,13809,15,7,0.0,0.0,0.0,0.0,0.0,0.112612,0.098129
4,1,13809,15,2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
5,1,62835,12,2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
6,1,62835,12,4,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
7,1,62835,12,1,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
8,1,62835,12,2,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
9,1,62835,12,5,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000

In [101]:
pd.pivot_table(data=combat, index=["server","acc_id", "day"], aggfunc=sum).head()

                   class  etc_cnt  num_opponent  pledge_cnt  \
server acc_id day
0      75     8        6      0.0           0.0         0.0
              9        6      0.0           0.0         0.0
              10       6      0.0           0.0         0.0
              11       6      0.0           0.0         0.0
              12       6      0.0           0.0         0.0

                   random_attacker_cnt  random_defender_cnt  same_pledge_cnt  \
server acc_id day
0      75     8                    0.0                  0.0              0.0
              9                    0.0                  0.0              0.0
              10                   0.0                  0.0              0.0
              11                   0.0                  0.0              0.0
              12                   0.0                  0.0              0.0

                   temp_cnt
server acc_id day
0      75     8         0.0
              9         0.0
              10        0.0
              11        0.0
              12        0.0

In [103]:
combat = pd.pivot_table(data=combat, index=["server","acc_id", "day"], aggfunc=sum)
combat.head()

                   class  etc_cnt  num_opponent  pledge_cnt  \
server acc_id day
0      75     8        6      0.0           0.0         0.0
              10       6      0.0           0.0         0.0
              11       6      0.0           0.0         0.0
              12       6      0.0           0.0         0.0
              13       6      0.0           0.0         0.0

                   random_attacker_cnt  random_defender_cnt  same_pledge_cnt  \
server acc_id day
0      75     8                    0.0                  0.0              0.0
              10                   0.0                  0.0              0.0
              11                   0.0                  0.0              0.0
              12                   0.0                  0.0              0.0
              13                   0.0                  0.0              0.0

                   temp_cnt
server acc_id day
0      75     8         0.0
              10        0.0
              11        0.0
              12        0.0
              13        0.0

## Payment

In [106]:
# 혹시 서버때문에 달라진 것은 아닌가?
total_payment = payment.groupby("acc_id")["amount_spent"].sum()
total_payment.head()

acc_id
8     1.404644
20    0.896531
21    2.695461
38    6.309749
41    0.035204
Name: amount_spent, dtype: float64

In [107]:
train_label[train_label["acc_id"] == 8]

###### Why are they different????? ####

      acc_id  survival_time  amount_spent  total_spent
5494       8             64       0.02031     1.299843

In [108]:
# Check the results
display(combat.tail())
display(payment.head())
display(pledge.head())
display(trade.head())
display(activity.head())

,,,class,etc_cnt,num_opponent,pledge_cnt,random_attacker_cnt,random_defender_cnt,same_pledge_cnt,temp_cnt
server,acc_id,day,,,,,,,,
1048,29385,1,215,0.112612,0.098129,0.000000,0.000000,0.000000,0.0,0.000000
1219,77673,23,68,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1258,33085,23,234,2.815288,5.004566,0.513474,4.555601,1.183064,0.0,1.439183
3696,40248,9,461,0.112612,0.098129,0.000000,0.000000,0.000000,0.0,0.000000
5244,119439,13,230,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

   day  acc_id  amount_spent
0   18   27835      0.826123
1   23   27835      0.011735
2   27   27835      0.035204
3   17   12351      0.528062
4   11  125437      0.633674

                   combat_char_cnt  combat_play_time  p_etc_cnt  \
server acc_id day
0      75     8           1.190948          1.883065   0.332678
              15          0.505250          0.451973   0.276052
              16          0.288715          0.404134   0.063704
              17          0.721786          0.902671   0.254818
              18          0.902233          0.979004   0.325600

                   non_combat_play_time  play_char_cnt  pledge_combat_cnt  \
server acc_id day
0      75     8                     0.0       4.402897           0.043710
              15                    0.0       1.118769           0.000000
              16                    0.0       1.190948           0.020034
              17                    0.0       2.165359           0.000000
              18                    0.0       2.345806           0.018213

                   p_random_attacker_cnt  p_random_defender_cnt  \
server acc_id day
0      75     8                 2.549816               0.429188
              15                0.000000               0.071531
              16                0.451866               0.214594
              17                0.000000               0.429188
              18                0.451866               0.357657

                   p_same_pledge_cnt  p_temp_cnt
server acc_id day
0      75     8             1.591434    1.977661
              15            0.000000    1.582129
              16            0.000000    0.791064
              17            0.000000    1.681012
              18            0.000000    2.373193

            time_bin  total_item_price  type
acc_id day
2      1         3.0      1.867780e-06   0.0
       2         1.0      6.393257e-03   1.0
       3         1.0      1.249094e-06   0.0
       5         0.0      1.998430e-09   0.0
       12        0.0      5.005340e-09   0.0

            boss_monster  death  enchant_count  exp_recovery  fishing  \
acc_id day
2      1               0    0.0            0.0           0.0      0.0
       2               0    0.0            0.0           0.0      0.0
       3               0    0.0            0.0           0.0      0.0
       4               0    0.0            0.0           0.0      0.0
       5               0    0.0            0.0           0.0      0.0

            fishing_prop  game_money_change  npc_kill  party_exp  playtime  \
acc_id day
2      1             0.0           1.022652       0.0        0.0  2.737490
       2             0.0          -1.042002       0.0        0.0  3.405864
       3             0.0           0.450366       0.0        0.0  3.412974
       4             0.0          -0.007215       0.0        0.0  3.412974
       5             0.0           0.015365       0.0        0.0  3.412974

            private_shop  quest_exp  revive  solo_exp  total_exp  server
acc_id day
2      1        2.493091        0.0     0.0       0.0        0.0    20.0
       2        3.188761        0.0     0.0       0.0        0.0    20.0
       3        3.223522        0.0     0.0       0.0        0.0    20.0
       4        3.171419        0.0     0.0       0.0        0.0    20.0
       5        3.175172        0.0     0.0       0.0        0.0    20.0

In [109]:
# Squeeze the whole dataframes into one
df = combat.join(pledge).join(trade).join(activity)

In [110]:
df.isnull().sum()

class                         0
etc_cnt                       0
num_opponent                  0
pledge_cnt                    0
random_attacker_cnt           0
random_defender_cnt           0
same_pledge_cnt               0
temp_cnt                      0
combat_char_cnt          490377
combat_play_time         490377
p_etc_cnt                490377
non_combat_play_time     490377
play_char_cnt            490377
pledge_combat_cnt        490377
p_random_attacker_cnt    490377
p_random_defender_cnt    490377
p_same_pledge_cnt        490377
p_temp_cnt               490377
time_bin                 725934
total_item_price         725934
type                     725934
boss_monster                  0
death                         0
enchant_count                 0
exp_recovery                  0
fishing                       0
fishing_prop                  0
game_money_change             0
npc_kill                      0
party_exp                     0
playtime                      0
private_shop                  0
quest_exp                     0
revive                        0
solo_exp                      0
total_exp                     0
server                        0
dtype: int64

In [111]:
df[100:200]

                   class   etc_cnt  num_opponent  pledge_cnt  \
acc_id day server
350    24  0           1  0.000000      0.000000    0.000000
       25  0           1  0.000000      0.000000    0.000000
       26  0           1  0.000000      0.000000    0.000000
       27  0           1  0.000000      0.392515    0.320921
       28  0           1  0.000000      0.000000    0.000000
371    1   0           3  0.000000      0.000000    0.000000
       2   0          10  0.000000      0.000000    0.000000
       3   0           8  0.000000      0.000000    0.000000
       4   0           1  0.000000      0.098129    0.000000
       5   0           1  0.000000      0.000000    0.000000
       6   0           1  0.000000      0.000000    0.000000
       7   0           1  0.000000      0.000000    0.000000
       8   0           1  0.000000      0.000000    0.000000
       9   0           1  0.112612      0.098129    0.000000
       10  0           8  0.000000      0.000000    0.000000
       11  0           1  0.000000      0.000000    0.000000
       12  0          10  0.000000      0.000000    0.000000
       13  0           3  0.000000      0.000000    0.000000
       14  0           8  0.000000      0.000000    0.000000
       15  0          10  0.000000      0.098129    0.000000
       16  0           1  0.000000      0.000000    0.000000
       17  0          10  0.000000      0.000000    0.000000
       18  0          10  0.225223      0.196258    0.000000
       19  0           1  0.000000      0.000000    0.000000
       20  0           1  0.000000      0.000000    0.000000
       21  0           3  0.000000      0.000000    0.000000
       22  0           8  0.000000      0.000000    0.000000
       23  0           8  0.000000      0.098129    0.000000
       24  0           3  0.000000      0.000000    0.000000
       25  0          10  0.225223      0.196258    0.000000
       26  0           1  0.000000      0.000000    0.000000
       27  0           8  0.000000      0.000000    0.000000
       28  0           1  0.000000      0.000000    0.000000
606    1   0           1  0.000000      0.000000    0.000000
       2   0           1  0.000000      0.000000    0.000000
       3   0           1  0.000000      0.000000    0.000000
       4   0           1  0.000000      0.000000    0.000000
       5   0           1  0.000000      0.098129    0.000000
       6   0           1  0.000000      0.098129    0.000000
       7   0           4  0.000000      0.196258    0.000000
       8   0           1  0.000000      0.000000    0.000000
       9   0           1  0.000000      0.000000    0.000000
       10  0           4  0.000000      0.000000    0.000000
       11  0           1  0.112612      0.098129    0.000000
       12  0           1  0.000000      0.000000    0.000000
       13  0           1  0.112612      0.098129    0.000000
       14  0           1  0.225223      0.294386    0.128368
       15  0           1  0.112612      0.098129    0.000000
       16  0           6  0.000000      0.000000    0.000000
       17  0           1  0.225223      0.196258    0.000000
       18  0           1  0.000000      0.000000    0.000000
       19  0           1  0.112612      0.196258    0.000000
       20  0           1  0.000000      0.000000    0.000000
       21  0           1  0.225223      0.098129    0.000000
       22  0           1  0.000000      0.000000    0.000000
       23  0          11  0.000000      0.000000    0.000000
       24  0           1  0.000000      0.000000    0.000000
       25  0           1  0.000000      0.000000    0.000000
       26  0           4  0.000000      0.000000    0.000000
       27  0           1  0.000000      0.000000    0.000000
       28  0          17  0.000000      0.098129    0.000000
637    1   0           5  0.000000      0.000000    0.000000
       2   0           5  0.000000      0.000000    0.000000
       3   0           1  0.000000      0.000000    0.000000
       4   0           1  0.000000      0.000000    0.000000
       6   0           1  0.000000      0.000000    0.000000
       7   0           1  0.000000      0.000000    0.000000
       8   0          10  0.000000      0.000000    0.000000
       9   0           1  0.000000      0.000000    0.000000
       10  0           1  0.000000      0.000000    0.000000
       11  0           1  0.000000      0.000000    0.000000
       12  0           1  0.000000      0.000000    0.000000
       13  0           5  0.000000      0.000000    0.000000
       14  0           1  0.000000      0.000000    0.000000
       15  0           1  0.000000      0.000000    0.000000
       17  0           1  0.000000      0.000000    0.000000
       22  0           4  0.000000      0.000000    0.000000
       23  0           1  0.000000      0.000000    0.000000
       24  0           1  0.675669      0.294386    0.000000
       25  0           1  1.013504      0.490644    0.000000
       26  0           1  0.000000      0.000000    0.000000
       27  0           1  0.000000      0.000000    0.000000
       28  0           1  0.000000      0.000000    0.000000
722    1   0           4  0.000000      0.000000    0.000000
       2   0           4  0.000000      0.098129    0.000000
       3   0           4  0.000000      0.000000    0.000000
       4   0           4  0.225223      0.098129    0.000000
       6   0           4  0.112612      0.098129    0.000000
       7   0           4  0.000000      0.098129    0.064184
       8   0           4  0.000000      0.098129    0.000000
       9   0           4  0.000000      0.000000    0.000000
       10  0           4  0.112612      0.098129    0.000000
       11  0           4  0.112612      0.196258    0.192553
       13  0           4  0.225223      0.196258    0.000000
       14  0           4  0.000000      0.000000    0.000000
       15  0           4  0.000000      0.196258    0.000000
       16  0           4  0.000000      0.000000    0.000000
       17  0           4  0.225223      0.196258    0.000000
       18  0           4  0.000000      0.294386    0.256737
       19  0           4  0.112612      0.392515    0.000000

                   random_attacker_cnt  random_defender_cnt  same_pledge_cnt  \
acc_id day server
350    24  0                       0.0             0.000000         0.000000
       25  0                       0.0             0.000000         0.000000
       26  0                       0.0             0.000000         0.000000
       27  0                       0.0             0.000000         0.000000
       28  0                       0.0             0.000000         0.000000
371    1   0                       0.0             0.000000         0.000000
       2   0                       0.0             0.000000         0.000000
       3   0                       0.0             0.000000         0.000000
       4   0                       0.0             1.183064         0.000000
       5   0                       0.0             0.000000         0.000000
       6   0                       0.0             0.000000         0.000000
       7   0                       0.0             0.000000         0.000000
       8   0                       0.0             0.000000         0.000000
       9   0                       0.0             0.000000         0.000000
       10  0                       0.0             0.000000         0.000000
       11  0                       0.0             0.000000         0.000000
       12  0                       0.0             0.000000         0.000000
       13  0                       0.0             0.000000         0.000000
       14  0                       0.0             0.000000         0.000000
       15  0                       0.0             1.183064         0.000000
       16  0                       0.0             0.000000         0.000000
       17  0                       0.0             0.000000         0.000000
       18  0                       0.0             0.000000         0.000000
       19  0                       0.0             0.000000         0.000000
       20  0                       0.0             0.000000         0.000000
       21  0                       0.0             0.000000         0.000000
       22  0                       0.0             0.000000         0.000000
       23  0                       0.0             0.000000         0.000000
       24  0                       0.0             0.000000         0.000000
       25  0                       0.0             0.000000         0.000000
       26  0                       0.0             0.000000         0.000000
       27  0                       0.0             0.000000         0.000000
       28  0                       0.0             0.000000         0.000000
606    1   0                       0.0             0.000000         0.000000
       2   0                       0.0             0.000000         0.000000
       3   0                       0.0             0.000000         0.000000
       4   0                       0.0             0.000000         0.000000
       5   0                       0.0             0.000000         0.000000
       6   0                       0.0             1.183064         0.000000
       7   0                       0.0             1.183064         0.000000
       8   0                       0.0             0.000000         0.000000
       9   0                       0.0             0.000000         0.000000
       10  0                       0.0             0.000000         0.000000
       11  0                       0.0             0.000000         0.000000
       12  0                       0.0             0.000000         0.000000
       13  0                       0.0             0.000000         0.000000
       14  0                       0.0             0.000000         0.000000
       15  0                       0.0             0.000000         0.000000
       16  0                       0.0             0.000000         0.000000
       17  0                       0.0             0.000000         0.000000
       18  0                       0.0             0.000000         0.000000
       19  0                       0.0             1.183064         0.000000
       20  0                       0.0             0.000000         0.000000
       21  0                       0.0             0.000000         0.000000
       22  0                       0.0             0.000000         0.000000
       23  0                       0.0             0.000000         0.000000
       24  0                       0.0             0.000000         0.000000
       25  0                       0.0             0.000000         0.000000
       26  0                       0.0             0.000000         0.000000
       27  0                       0.0             0.000000         0.000000
       28  0                       0.0             0.000000         0.000000
637    1   0                       0.0             0.000000         0.000000
       2   0                       0.0             0.000000         0.000000
       3   0                       0.0             0.000000         0.000000
       4   0                       0.0             0.000000         0.000000
       6   0                       0.0             0.000000         0.000000
       7   0                       0.0             0.000000         0.000000
       8   0                       0.0             0.000000         0.000000
       9   0                       0.0             0.000000         0.000000
       10  0                       0.0             0.000000         0.000000
       11  0                       0.0             0.000000         0.000000
       12  0                       0.0             0.000000         0.000000
       13  0                       0.0             0.000000         0.000000
       14  0                       0.0             0.000000         0.000000
       15  0                       0.0             0.000000         0.000000
       17  0                       0.0             0.000000         0.000000
       22  0                       0.0             0.000000         0.000000
       23  0                       0.0             0.000000         0.000000
       24  0                       0.0             0.000000         0.000000
       25  0                       0.0             0.000000         0.000000
       26  0                       0.0             0.000000         0.000000
       27  0                       0.0             0.000000         0.000000
       28  0                       0.0             0.000000         0.000000
722    1   0                       0.0             0.000000         0.000000
       2   0                       0.0             0.000000         0.000000
       3   0                       0.0             0.000000         0.000000
       4   0                       0.0             0.000000         0.000000
       6   0                       0.0             0.000000         0.000000
       7   0                       0.0             0.000000         0.000000
       8   0                       0.0             1.183064         0.000000
       9   0                       0.0             0.000000         0.000000
       10  0                       0.0             0.000000         0.000000
       11  0                       0.0             0.000000         0.000000
       13  0                       0.0             0.000000         0.000000
       14  0                       0.0             0.000000         0.000000
       15  0                       0.0             1.183064         0.000000
       16  0                       0.0             0.000000         0.000000
       17  0                       0.0             0.000000         0.000000
       18  0                       0.0             0.000000         0.000000
       19  0                       0.0             1.183064        12.398273

                   temp_cnt  combat_char_cnt  combat_play_time  p_etc_cnt  \
acc_id day server
350    24  0       0.000000         0.685697          1.931714   0.226504
       25  0       0.000000         0.866144          2.290790   0.460087
       26  0       0.000000         1.154858          2.885235   1.528905
       27  0       0.000000         1.046590          2.539248   0.460087
       28  0       0.000000         0.938322          2.718554   0.792766
371    1   0       0.000000         0.144357          0.893173   0.092017
       2   0       0.000000         0.505250          2.713458   0.127409
       3   0       0.000000         0.360893          2.409054   0.070783
       4   0       0.000000         0.252625          1.144411   0.070783
       5   0       0.000000         0.252625          1.284219   0.035391
       6   0       0.000000         0.180447          1.232790   0.070783
       7   0       0.000000         0.252625          1.350011   0.148644
       8   0       0.000000         0.324804          0.931861   0.120331
       9   0       0.000000         0.396983          1.099121   0.113252
       10  0       0.000000         0.433072          2.285810   0.056626
       11  0       0.000000         0.324804          1.077924   0.099096
       12  0       0.000000         0.360893          2.255462   0.084939
       13  0       0.000000         0.180447          1.039004   0.070783
       14  0       0.000000         0.649608          2.749597   0.155722
       15  0       0.000000         0.577429          1.640167   0.212348
       16  0       0.000000         0.288715          1.013290   0.212348
       17  0       0.000000         1.082680          4.043777   0.467166
       18  0       0.000000         1.190948          3.933622   0.233583
       19  0       0.000000         0.108268          1.428660   0.035391
       20  0       0.000000         0.108268          1.097152   0.014157
       21  0       0.000000         0.433072          2.664809   0.127409
       22  0       0.000000         0.721786          2.851528   0.169878
       23  0       0.479728         0.360893          1.683257   0.000000
       24  0       0.000000         0.505250          2.959020   0.254818
       25  0       0.000000         0.866144          4.231424   0.106174
       26  0       0.000000         0.252625          1.474297   0.092017
       27  0       0.000000         1.046590          4.123122   0.608731
       28  0       0.000000         0.144357          1.568352   0.014157
606    1   0       0.000000         0.252625          0.600236   0.070783
       2   0       0.000000         0.180447          0.748848   0.063704
       3   0       0.000000         0.072179          0.534097   0.042470
       4   0       0.000000         0.036089          0.728693   0.000000
       5   0       0.479728         0.288715          0.777342   0.056626
       6   0       0.000000         0.216536          0.635912   0.056626
       7   0       0.479728         0.036089          0.649580   0.000000
       8   0       0.000000         0.216536          0.643094   0.198191
       9   0       0.000000         0.252625          0.767381   0.219426
       10  0       0.000000         0.144357          0.857266   0.021235
       11  0       0.000000         0.216536          0.679233   0.084939
       12  0       0.000000         0.180447          0.809427   0.113252
       13  0       0.000000         0.180447          0.705759   0.042470
       14  0       0.000000         0.288715          0.666492   0.056626
       15  0       0.000000         0.288715          0.546143   0.063704
       16  0       0.000000         0.216536          0.598499   0.084939
       17  0       0.000000         0.216536          0.739350   0.148644
       18  0       0.000000         0.144357          0.646453   0.000000
       19  0       0.000000         0.180447          0.486375   0.042470
       20  0       0.000000         0.072179          0.596182   0.049548
       21  0       0.000000         0.144357          0.696029   0.134487
       22  0       0.000000         0.108268          0.525873   0.028313
       23  0       0.000000         0.216536          0.614020   0.049548
       24  0       0.000000         0.252625          1.052441   0.226504
       25  0       0.000000         0.180447          0.597804   0.063704
       26  0       0.000000         0.216536          0.608576   0.084939
       27  0       0.000000         0.180447          0.936957   0.113252
       28  0       0.479728         0.324804          1.015838   0.247739
637    1   0       0.000000         0.577429          0.925606   0.268974
       2   0       0.000000         0.505250          1.069468   0.169878
       3   0       0.000000         0.433072          0.837806   0.134487
       4   0       0.000000         0.433072          0.903135   0.056626
       6   0       0.000000         0.324804          0.782207   0.028313
       7   0       0.000000         0.180447          0.612051   0.099096
       8   0       0.000000         0.108268          0.434366   0.021235
       9   0       0.000000         0.108268          0.679697   0.042470
       10  0       0.000000         0.252625          0.439231   0.226504
       11  0       0.000000         0.180447          0.566645   0.240661
       12  0       0.000000         0.108268          0.563634   0.035391
       13  0       0.000000         0.000000          0.000000   0.000000
       14  0       0.000000              NaN               NaN        NaN
       15  0       0.000000              NaN               NaN        NaN
       17  0       0.000000              NaN               NaN        NaN
       22  0       0.000000              NaN               NaN        NaN
       23  0       0.000000              NaN               NaN        NaN
       24  0       0.000000              NaN               NaN        NaN
       25  0       0.000000              NaN               NaN        NaN

In [112]:
combat.columns

Index(['class', 'etc_cnt', 'num_opponent', 'pledge_cnt', 'random_attacker_cnt',
       'random_defender_cnt', 'same_pledge_cnt', 'temp_cnt'],
      dtype='object')

In [113]:
# 네트워크 분석을 위해서 주요 분석해야 할 피쳐
# 거래적 축면 : 만약 파밍만 주요로 하는 작업장이라면 어떻게 분류해야 하는가?
# 그것을 오히려 버려야 하는 클러스터인가? 아니면 그냥 놔두면 되는 클러스터인가?
# 혈맹적 측면 : 혈맹끼리 잘 뭉쳐있으면 어떤식으로 점수를 부가해야 하는가
# 혈맹 아이디로 얼마나 모야있는지?
# 이 외에 어떻게 클러스터를 만들어서 분석해야하는가? 생각